// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: eolymp/judge/registration_service.proto

package judge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistrationService_DescribeRegistration_FullMethodName = "/eolymp.judge.RegistrationService/DescribeRegistration"
	RegistrationService_SubmitRegistration_FullMethodName   = "/eolymp.judge.RegistrationService/SubmitRegistration"
)

// RegistrationServiceClient is the client API for RegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegistrationService lets people sign themselves up for a contest instead of waiting for an organiser to
// assign them.
//
// A contest can ask its registrants for details about themselves, expressed as the same attributes the
// space keeps on its members, and this service both publishes that form and takes the answers back. It
// is called by the contest client; there is no organiser-facing screen behind it, and organisers add
// people through ParticipantService instead. Registering is not the same as being admitted: where a
// contest requires admission, a registrant still has to be admitted through AdmissionService.
type RegistrationServiceClient interface {
	// DescribeRegistration returns the form the contest asks its registrants to fill in, alongside the
	// values already on record for the caller so the form can be shown pre-filled rather than empty.
	// A contest that asks for nothing returns an empty form.
	DescribeRegistration(ctx context.Context, in *DescribeRegistrationInput, opts ...grpc.CallOption) (*DescribeRegistrationOutput, error)
	// SubmitRegistration stores the caller's answers to the registration form and signs them up for the
	// contest, replacing the deprecated JoinContest. It can be called again to correct answers that were
	// already submitted.
	SubmitRegistration(ctx context.Context, in *SubmitRegistrationInput, opts ...grpc.CallOption) (*SubmitRegistrationOutput, error)
}

type registrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationServiceClient(cc grpc.ClientConnInterface) RegistrationServiceClient {
	return &registrationServiceClient{cc}
}

func (c *registrationServiceClient) DescribeRegistration(ctx context.Context, in *DescribeRegistrationInput, opts ...grpc.CallOption) (*DescribeRegistrationOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeRegistrationOutput)
	err := c.cc.Invoke(ctx, RegistrationService_DescribeRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) SubmitRegistration(ctx context.Context, in *SubmitRegistrationInput, opts ...grpc.CallOption) (*SubmitRegistrationOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRegistrationOutput)
	err := c.cc.Invoke(ctx, RegistrationService_SubmitRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServiceServer is the server API for RegistrationService service.
// All implementations should embed UnimplementedRegistrationServiceServer
// for forward compatibility.
//
// RegistrationService lets people sign themselves up for a contest instead of waiting for an organiser to
// assign them.
//
// A contest can ask its registrants for details about themselves, expressed as the same attributes the
// space keeps on its members, and this service both publishes that form and takes the answers back. It
// is called by the contest client; there is no organiser-facing screen behind it, and organisers add
// people through ParticipantService instead. Registering is not the same as being admitted: where a
// contest requires admission, a registrant still has to be admitted through AdmissionService.
type RegistrationServiceServer interface {
	// DescribeRegistration returns the form the contest asks its registrants to fill in, alongside the
	// values already on record for the caller so the form can be shown pre-filled rather than empty.
	// A contest that asks for nothing returns an empty form.
	DescribeRegistration(context.Context, *DescribeRegistrationInput) (*DescribeRegistrationOutput, error)
	// SubmitRegistration stores the caller's answers to the registration form and signs them up for the
	// contest, replacing the deprecated JoinContest. It can be called again to correct answers that were
	// already submitted.
	SubmitRegistration(context.Context, *SubmitRegistrationInput) (*SubmitRegistrationOutput, error)
}

// UnimplementedRegistrationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServiceServer struct{}

func (UnimplementedRegistrationServiceServer) DescribeRegistration(context.Context, *DescribeRegistrationInput) (*DescribeRegistrationOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) SubmitRegistration(context.Context, *SubmitRegistrationInput) (*SubmitRegistrationOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) testEmbeddedByValue() {}

// UnsafeRegistrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServiceServer will
// result in compilation errors.
type UnsafeRegistrationServiceServer interface {
	mustEmbedUnimplementedRegistrationServiceServer()
}

func RegisterRegistrationServiceServer(s grpc.ServiceRegistrar, srv RegistrationServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistrationService_ServiceDesc, srv)
}

func _RegistrationService_DescribeRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRegistrationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).DescribeRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_DescribeRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).DescribeRegistration(ctx, req.(*DescribeRegistrationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_SubmitRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRegistrationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).SubmitRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_SubmitRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).SubmitRegistration(ctx, req.(*SubmitRegistrationInput))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistrationService_ServiceDesc is the grpc.ServiceDesc for RegistrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eolymp.judge.RegistrationService",
	HandlerType: (*RegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeRegistration",
			Handler:    _RegistrationService_DescribeRegistration_Handler,
		},
		{
			MethodName: "SubmitRegistration",
			Handler:    _RegistrationService_SubmitRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eolymp/judge/registration_service.proto",
}
