// Code generated by protoc-gen-go-server. DO NOT EDIT.
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-go-server for more details.

package judge

import (
	errors "errors"
	go_querystring "github.com/eolymp/go-querystring"
	wellknown "github.com/eolymp/go-sdk/eolymp/wellknown"
	mux "github.com/gorilla/mux"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	metadata "google.golang.org/grpc/metadata"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	io "io"
	http "net/http"
	url "net/url"
	strconv "strconv"
	time "time"
)

var errSubmissionServiceRequestTooLarge = errors.New("request too large")

// _SubmissionService_HTTPInvalidArgument wraps a request parsing error into an InvalidArgument status
// with structured details so it is reported as HTTP 400 instead of 500.
func _SubmissionService_HTTPInvalidArgument(err error) error {
	s, derr := status.New(codes.InvalidArgument, err.Error()).WithDetails(&wellknown.InvalidArgument{
		Validation: []*wellknown.Validation{{ErrorMessage: err.Error()}},
	})
	if derr != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}

	return s.Err()
}

// _SubmissionService_HTTPReadQueryString parses query string into proto.Message with size limit
func _SubmissionService_HTTPReadQueryString(r *http.Request, v proto.Message, maxSize int64) error {
	if int64(len(r.URL.RawQuery)) > maxSize {
		return errSubmissionServiceRequestTooLarge
	}

	if h := r.Header.Values("Strict-Parsing"); len(h) > 0 {
		strict, err := strconv.ParseBool(h[len(h)-1])
		if err != nil {
			return _SubmissionService_HTTPInvalidArgument(err)
		}

		if strict {
			query, err := url.ParseQuery(r.URL.RawQuery)
			if err != nil {
				return _SubmissionService_HTTPInvalidArgument(err)
			}

			if err := go_querystring.UnmarshalStrict(query, v); err != nil {
				return _SubmissionService_HTTPInvalidArgument(err)
			}

			return nil
		}
	}

	if err := go_querystring.Unmarshal(r.URL.Query(), v); err != nil {
		return _SubmissionService_HTTPInvalidArgument(err)
	}

	return nil
}

// _SubmissionService_HTTPReadRequestBody parses body into proto.Message with size limit
func _SubmissionService_HTTPReadRequestBody(r *http.Request, v proto.Message, maxSize int64) error {
	data, err := io.ReadAll(http.MaxBytesReader(nil, r.Body, maxSize))
	if err != nil {
		if err.Error() == "http: request body too large" {
			return errSubmissionServiceRequestTooLarge
		}
		return err
	}

	// an empty body is a valid, empty message
	if len(data) == 0 {
		return nil
	}

	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, v)); err != nil {
		return _SubmissionService_HTTPInvalidArgument(err)
	}

	return nil
}

// _SubmissionService_HTTPReadRequest reads request parameters from the body when it is present,
// otherwise it falls back to the query string. Used for verbs (DELETE) that may carry parameters either way.
func _SubmissionService_HTTPReadRequest(r *http.Request, v proto.Message, bodyMaxSize, queryMaxSize int64) error {
	data, err := io.ReadAll(http.MaxBytesReader(nil, r.Body, bodyMaxSize))
	if err != nil {
		if err.Error() == "http: request body too large" {
			return errSubmissionServiceRequestTooLarge
		}
		return err
	}

	// when a body is present it takes precedence over the query string
	if len(data) != 0 {
		if err := (protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, v)); err != nil {
			return _SubmissionService_HTTPInvalidArgument(err)
		}

		return nil
	}

	return _SubmissionService_HTTPReadQueryString(r, v, queryMaxSize)
}

// _SubmissionService_HTTPWriteResponse writes proto.Message to HTTP response
func _SubmissionService_HTTPWriteResponse(w http.ResponseWriter, v proto.Message, h, t metadata.MD) {
	data, err := protojson.Marshal(v)
	if err != nil {
		_SubmissionService_HTTPWriteErrorResponse(w, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")

	if v := append(h.Get("cache-control"), t.Get("cache-control")...); len(v) > 0 {
		w.Header().Set("Cache-Control", v[len(v)-1])
	}

	if v := append(h.Get("etag"), t.Get("etag")...); len(v) > 0 {
		w.Header().Set("ETag", v[len(v)-1])
	}

	if v := append(h.Get("last-modified"), t.Get("last-modified")...); len(v) > 0 {
		w.Header().Set("Last-Modified", v[len(v)-1])
	}

	w.WriteHeader(http.StatusOK)

	_, _ = w.Write(data)
}

// _SubmissionService_HTTPWriteErrorResponse writes error to HTTP response with error status code
func _SubmissionService_HTTPWriteErrorResponse(w http.ResponseWriter, e error) {
	s := status.Convert(e)

	if e == errSubmissionServiceRequestTooLarge {
		w.WriteHeader(http.StatusRequestEntityTooLarge)
		_, _ = w.Write([]byte("request too large"))
		return
	}

	w.Header().Set("Content-Type", "application/json")

	switch s.Code() {
	case codes.OK:
		w.WriteHeader(http.StatusOK)
	case codes.Canceled:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.Unknown:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.InvalidArgument:
		w.WriteHeader(http.StatusBadRequest)
	case codes.DeadlineExceeded:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.NotFound:
		w.WriteHeader(http.StatusNotFound)
	case codes.AlreadyExists:
		w.WriteHeader(http.StatusConflict)
	case codes.PermissionDenied:
		w.WriteHeader(http.StatusForbidden)
	case codes.ResourceExhausted:
		w.WriteHeader(http.StatusTooManyRequests)
	case codes.FailedPrecondition:
		w.WriteHeader(http.StatusPreconditionFailed)
	case codes.Aborted:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.OutOfRange:
		w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
	case codes.Unimplemented:
		w.WriteHeader(http.StatusNotImplemented)
	case codes.Internal:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unavailable:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.DataLoss:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unauthenticated:
		w.WriteHeader(http.StatusUnauthorized)
	default:
		w.WriteHeader(http.StatusInternalServerError)
	}

	data, err := protojson.Marshal(s.Proto())
	if err != nil {
		panic(err)
	}

	_, _ = w.Write(data)
}

// _SubmissionService_HTTPWriteEventStream streams messages from recv to HTTP response as server-sent events
func _SubmissionService_HTTPWriteEventStream(w http.ResponseWriter, r *http.Request, recv func() (proto.Message, error)) {
	ctrl := http.NewResponseController(w)

	_ = ctrl.SetWriteDeadline(time.Time{})

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache, no-transform")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")

	if err := ctrl.Flush(); err != nil {
		_SubmissionService_HTTPWriteErrorResponse(w, status.Error(codes.Internal, "event streams are not supported by this server"))
		return
	}

	type event struct {
		out proto.Message
		err error
	}

	queue := make(chan event)

	go func() {
		defer close(queue)

		for {
			out, err := recv()

			select {
			case queue <- event{out, err}:
			case <-r.Context().Done():
				return
			}

			if err != nil {
				return
			}
		}
	}()

	heartbeat := time.NewTicker(20 * time.Second)
	defer heartbeat.Stop()

	for {
		select {
		case <-r.Context().Done():
			return
		case <-heartbeat.C:
			if _, err := w.Write([]byte(": ping\n\n")); err != nil {
				return
			}

			_ = ctrl.Flush()
		case e, ok := <-queue:
			if !ok {
				return
			}

			if e.err != nil {
				if errors.Is(e.err, io.EOF) {
					_, _ = w.Write([]byte("event: eof\ndata: {}\n\n"))
				} else {
					_SubmissionService_HTTPWriteEvent(w, "error", status.Convert(e.err).Proto())
				}

				_ = ctrl.Flush()

				return
			}

			_SubmissionService_HTTPWriteEvent(w, "", e.out)

			_ = ctrl.Flush()
		}
	}
}

// _SubmissionService_HTTPWriteEvent writes single server-sent event, unnamed when name is empty
func _SubmissionService_HTTPWriteEvent(w http.ResponseWriter, name string, v proto.Message) {
	data, err := protojson.Marshal(v)
	if err != nil {
		return
	}

	if name != "" {
		_, _ = w.Write([]byte("event: " + name + "\n"))
	}

	_, _ = w.Write([]byte("data: "))
	_, _ = w.Write(data)
	_, _ = w.Write([]byte("\n\n"))
}

// RegisterSubmissionServiceHttpHandlers adds handlers for for SubmissionServiceClient
func RegisterSubmissionServiceHttpHandlers(router *mux.Router, prefix string, cli SubmissionServiceClient) {
	router.Handle(prefix+"/problems/{problem_id}/submissions", _SubmissionService_CreateSubmission_Rule0(cli)).
		Methods("POST").
		Name("eolymp.judge.SubmissionService.CreateSubmission")
	router.Handle(prefix+"/submissions", _SubmissionService_ListSubmissions_Rule0(cli)).
		Methods("GET").
		Name("eolymp.judge.SubmissionService.ListSubmissions")
	router.Handle(prefix+"/submissions/{submission_id}", _SubmissionService_DescribeSubmission_Rule0(cli)).
		Methods("GET").
		Name("eolymp.judge.SubmissionService.DescribeSubmission")
	router.Handle(prefix+"/submissions/{submission_id}/print", _SubmissionService_PrintSubmission_Rule0(cli)).
		Methods("POST").
		Name("eolymp.judge.SubmissionService.PrintSubmission")
	router.Handle(prefix+"/submissions/{submission_id}/watch", _SubmissionService_WatchSubmission_Rule0(cli)).
		Methods("GET").
		Name("eolymp.judge.SubmissionService.WatchSubmission")
	router.Handle(prefix+"/submissions:watch", _SubmissionService_WatchSubmissionList_Rule0(cli)).
		Methods("GET").
		Name("eolymp.judge.SubmissionService.WatchSubmissionList")
	router.Handle(prefix+"/submissions/{submission_id}/retest", _SubmissionService_RetestSubmission_Rule0(cli)).
		Methods("POST").
		Name("eolymp.judge.SubmissionService.RetestSubmission")
	router.Handle(prefix+"/submissions/{submission_id}", _SubmissionService_DeleteSubmission_Rule0(cli)).
		Methods("DELETE").
		Name("eolymp.judge.SubmissionService.DeleteSubmission")
	router.Handle(prefix+"/submissions/{submission_id}/restore", _SubmissionService_RestoreSubmission_Rule0(cli)).
		Methods("POST").
		Name("eolymp.judge.SubmissionService.RestoreSubmission")
	router.Handle(prefix+"/problems/{problem_id}/retest", _SubmissionService_RetestProblem_Rule0(cli)).
		Methods("GET").
		Name("eolymp.judge.SubmissionService.RetestProblem")
	router.Handle(prefix+"/submissions/{submission_id}/analyze", _SubmissionService_AnalyzeSubmission_Rule0(cli)).
		Methods("POST").
		Name("eolymp.judge.SubmissionService.AnalyzeSubmission")
}

// RegisterSubmissionServiceHttpProxy adds proxy handlers for for SubmissionServiceClient
func RegisterSubmissionServiceHttpProxy(router *mux.Router, prefix string, conn grpc.ClientConnInterface) {
	RegisterSubmissionServiceHttpHandlers(router, prefix, NewSubmissionServiceClient(conn))
}

func _SubmissionService_CreateSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &CreateSubmissionInput{}

		if err := _SubmissionService_HTTPReadRequestBody(r, in, 5242880); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ProblemId = vars["problem_id"]

		var header, trailer metadata.MD

		out, err := cli.CreateSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_ListSubmissions_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListSubmissionsInput{}

		if err := _SubmissionService_HTTPReadQueryString(r, in, 131072); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		var header, trailer metadata.MD

		out, err := cli.ListSubmissions(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_DescribeSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeSubmissionInput{}

		if err := _SubmissionService_HTTPReadQueryString(r, in, 131072); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		var header, trailer metadata.MD

		out, err := cli.DescribeSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_PrintSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &PrintSubmissionInput{}

		if err := _SubmissionService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		var header, trailer metadata.MD

		out, err := cli.PrintSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_WatchSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &WatchSubmissionInput{}

		if err := _SubmissionService_HTTPReadQueryString(r, in, 131072); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		stream, err := cli.WatchSubmission(r.Context(), in)
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteEventStream(w, r, func() (proto.Message, error) { return stream.Recv() })
	})
}

func _SubmissionService_WatchSubmissionList_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &WatchSubmissionListInput{}

		if err := _SubmissionService_HTTPReadQueryString(r, in, 131072); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		stream, err := cli.WatchSubmissionList(r.Context(), in)
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteEventStream(w, r, func() (proto.Message, error) { return stream.Recv() })
	})
}

func _SubmissionService_RetestSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &RetestSubmissionInput{}

		if err := _SubmissionService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		var header, trailer metadata.MD

		out, err := cli.RetestSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_DeleteSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DeleteSubmissionInput{}

		if err := _SubmissionService_HTTPReadRequest(r, in, 1048576, 131072); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		var header, trailer metadata.MD

		out, err := cli.DeleteSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_RestoreSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &RestoreSubmissionInput{}

		if err := _SubmissionService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		var header, trailer metadata.MD

		out, err := cli.RestoreSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_RetestProblem_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &RetestProblemInput{}

		if err := _SubmissionService_HTTPReadQueryString(r, in, 131072); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ProblemId = vars["problem_id"]

		var header, trailer metadata.MD

		out, err := cli.RetestProblem(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _SubmissionService_AnalyzeSubmission_Rule0(cli SubmissionServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &AnalyzeSubmissionInput{}

		if err := _SubmissionService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.SubmissionId = vars["submission_id"]

		var header, trailer metadata.MD

		out, err := cli.AnalyzeSubmission(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_SubmissionService_HTTPWriteErrorResponse(w, err)
			return
		}

		_SubmissionService_HTTPWriteResponse(w, out, header, trailer)
	})
}
