// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: eolymp/ecm/node.proto

package ecm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Attr          map[string]string      `protobuf:"bytes,2,rep,name=attr,proto3" json:"attr,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Children      []*Node                `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_eolymp_ecm_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_ecm_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_eolymp_ecm_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetAttr() map[string]string {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *Node) GetChildren() []*Node {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_eolymp_ecm_node_proto protoreflect.FileDescriptor

const file_eolymp_ecm_node_proto_rawDesc = "" +
	"\n" +
	"\x15eolymp/ecm/node.proto\x12\n" +
	"eolymp.ecm\"\xb1\x01\n" +
	"\x04Node\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12.\n" +
	"\x04attr\x18\x02 \x03(\v2\x1a.eolymp.ecm.Node.AttrEntryR\x04attr\x12,\n" +
	"\bchildren\x18\x03 \x03(\v2\x10.eolymp.ecm.NodeR\bchildren\x1a7\n" +
	"\tAttrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B)Z'github.com/eolymp/go-sdk/eolymp/ecm;ecmb\x06proto3"

var (
	file_eolymp_ecm_node_proto_rawDescOnce sync.Once
	file_eolymp_ecm_node_proto_rawDescData []byte
)

func file_eolymp_ecm_node_proto_rawDescGZIP() []byte {
	file_eolymp_ecm_node_proto_rawDescOnce.Do(func() {
		file_eolymp_ecm_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eolymp_ecm_node_proto_rawDesc), len(file_eolymp_ecm_node_proto_rawDesc)))
	})
	return file_eolymp_ecm_node_proto_rawDescData
}

var file_eolymp_ecm_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_eolymp_ecm_node_proto_goTypes = []any{
	(*Node)(nil), // 0: eolymp.ecm.Node
	nil,          // 1: eolymp.ecm.Node.AttrEntry
}
var file_eolymp_ecm_node_proto_depIdxs = []int32{
	1, // 0: eolymp.ecm.Node.attr:type_name -> eolymp.ecm.Node.AttrEntry
	0, // 1: eolymp.ecm.Node.children:type_name -> eolymp.ecm.Node
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eolymp_ecm_node_proto_init() }
func file_eolymp_ecm_node_proto_init() {
	if File_eolymp_ecm_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eolymp_ecm_node_proto_rawDesc), len(file_eolymp_ecm_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eolymp_ecm_node_proto_goTypes,
		DependencyIndexes: file_eolymp_ecm_node_proto_depIdxs,
		MessageInfos:      file_eolymp_ecm_node_proto_msgTypes,
	}.Build()
	File_eolymp_ecm_node_proto = out.File
	file_eolymp_ecm_node_proto_goTypes = nil
	file_eolymp_ecm_node_proto_depIdxs = nil
}
