// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: eolymp/scoreboard/scoreboard.proto

package scoreboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scoreboard_Mode int32

const (
	Scoreboard_UNKNOWN_MODE Scoreboard_Mode = 0
	// Standings counting contest time only.
	Scoreboard_MAIN Scoreboard_Mode = 1
	// Standings where a contest that is currently frozen shows its results as of its own freezing time, and
	// one that is not contributes the same values as MAIN.
	Scoreboard_FROZEN Scoreboard_Mode = 2
	// Standings counting upsolve submissions.
	Scoreboard_UPSOLVE Scoreboard_Mode = 3
)

// Enum value maps for Scoreboard_Mode.
var (
	Scoreboard_Mode_name = map[int32]string{
		0: "UNKNOWN_MODE",
		1: "MAIN",
		2: "FROZEN",
		3: "UPSOLVE",
	}
	Scoreboard_Mode_value = map[string]int32{
		"UNKNOWN_MODE": 0,
		"MAIN":         1,
		"FROZEN":       2,
		"UPSOLVE":      3,
	}
)

func (x Scoreboard_Mode) Enum() *Scoreboard_Mode {
	p := new(Scoreboard_Mode)
	*p = x
	return p
}

func (x Scoreboard_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scoreboard_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_eolymp_scoreboard_scoreboard_proto_enumTypes[0].Descriptor()
}

func (Scoreboard_Mode) Type() protoreflect.EnumType {
	return &file_eolymp_scoreboard_scoreboard_proto_enumTypes[0]
}

func (x Scoreboard_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scoreboard_Mode.Descriptor instead.
func (Scoreboard_Mode) EnumDescriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0, 0}
}

type Scoreboard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Must match [a-z][a-z0-9\-_]+. Unique within a space, and accepted anywhere the scoreboard id is.
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Count only this many best contests per member towards the total; zero counts all of them.
	BestOf        uint32                `protobuf:"varint,4,opt,name=best_of,json=bestOf,proto3" json:"best_of,omitempty"`
	Modes         []Scoreboard_Mode     `protobuf:"varint,7,rep,packed,name=modes,proto3,enum=eolymp.scoreboard.Scoreboard_Mode" json:"modes,omitempty"`
	Contests      []*Scoreboard_Contest `protobuf:"bytes,10,rep,name=contests,proto3" json:"contests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scoreboard) Reset() {
	*x = Scoreboard{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard) ProtoMessage() {}

func (x *Scoreboard) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard.ProtoReflect.Descriptor instead.
func (*Scoreboard) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0}
}

func (x *Scoreboard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scoreboard) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Scoreboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scoreboard) GetBestOf() uint32 {
	if x != nil {
		return x.BestOf
	}
	return 0
}

func (x *Scoreboard) GetModes() []Scoreboard_Mode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *Scoreboard) GetContests() []*Scoreboard_Contest {
	if x != nil {
		return x.Contests
	}
	return nil
}

type Row struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MemberId    string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Index       uint32                 `protobuf:"varint,10,opt,name=index,proto3" json:"index,omitempty"`
	// Rank among officially ranked members only; zero when the row itself is unofficial or disqualified.
	Rank       uint32 `protobuf:"varint,11,opt,name=rank,proto3" json:"rank,omitempty"`
	RankLength uint32 `protobuf:"varint,12,opt,name=rank_length,json=rankLength,proto3" json:"rank_length,omitempty"`
	// Rank among every member, including unofficial and disqualified ones. Always set.
	RankAll       uint32              `protobuf:"varint,13,opt,name=rank_all,json=rankAll,proto3" json:"rank_all,omitempty"`
	RankAllLength uint32              `protobuf:"varint,14,opt,name=rank_all_length,json=rankAllLength,proto3" json:"rank_all_length,omitempty"`
	Score         float32             `protobuf:"fixed32,20,opt,name=score,proto3" json:"score,omitempty"`
	Penalty       float32             `protobuf:"fixed32,21,opt,name=penalty,proto3" json:"penalty,omitempty"`
	Unofficial    bool                `protobuf:"varint,30,opt,name=unofficial,proto3" json:"unofficial,omitempty"`
	Disqualified  bool                `protobuf:"varint,31,opt,name=disqualified,proto3" json:"disqualified,omitempty"`
	Contests      []*Row_ContestScore `protobuf:"bytes,50,rep,name=contests,proto3" json:"contests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Row) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Row) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Row) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Row) GetRankLength() uint32 {
	if x != nil {
		return x.RankLength
	}
	return 0
}

func (x *Row) GetRankAll() uint32 {
	if x != nil {
		return x.RankAll
	}
	return 0
}

func (x *Row) GetRankAllLength() uint32 {
	if x != nil {
		return x.RankAllLength
	}
	return 0
}

func (x *Row) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Row) GetPenalty() float32 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *Row) GetUnofficial() bool {
	if x != nil {
		return x.Unofficial
	}
	return false
}

func (x *Row) GetDisqualified() bool {
	if x != nil {
		return x.Disqualified
	}
	return false
}

func (x *Row) GetContests() []*Row_ContestScore {
	if x != nil {
		return x.Contests
	}
	return nil
}

type Scoreboard_Contest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ContestId string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Index     uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Read-only, resolved from the contest.
	Name          string                `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                `protobuf:"bytes,11,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Problems      []*Scoreboard_Problem `protobuf:"bytes,20,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scoreboard_Contest) Reset() {
	*x = Scoreboard_Contest{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard_Contest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard_Contest) ProtoMessage() {}

func (x *Scoreboard_Contest) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard_Contest.ProtoReflect.Descriptor instead.
func (*Scoreboard_Contest) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Scoreboard_Contest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *Scoreboard_Contest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Scoreboard_Contest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scoreboard_Contest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Scoreboard_Contest) GetProblems() []*Scoreboard_Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type Scoreboard_Problem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProblemId string                 `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Index     uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Letter or number the contest gives the problem.
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scoreboard_Problem) Reset() {
	*x = Scoreboard_Problem{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard_Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard_Problem) ProtoMessage() {}

func (x *Scoreboard_Problem) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard_Problem.ProtoReflect.Descriptor instead.
func (*Scoreboard_Problem) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Scoreboard_Problem) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Scoreboard_Problem) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Scoreboard_Problem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Scoreboard_Patch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          *string                `protobuf:"bytes,2,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BestOf        *uint32                `protobuf:"varint,4,opt,name=best_of,json=bestOf,proto3,oneof" json:"best_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scoreboard_Patch) Reset() {
	*x = Scoreboard_Patch{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard_Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard_Patch) ProtoMessage() {}

func (x *Scoreboard_Patch) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard_Patch.ProtoReflect.Descriptor instead.
func (*Scoreboard_Patch) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Scoreboard_Patch) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *Scoreboard_Patch) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Scoreboard_Patch) GetBestOf() uint32 {
	if x != nil && x.BestOf != nil {
		return *x.BestOf
	}
	return 0
}

type Row_ProblemScore struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProblemId  string                 `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Score      float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Penalty    float32                `protobuf:"fixed32,3,opt,name=penalty,proto3" json:"penalty,omitempty"`
	Percentage float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Attempts   uint32                 `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Time       uint32                 `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	// Attempts made after the contest was frozen and therefore not reflected in score. Highlight a cell as
	// stale when pending is above zero OR changed is set: a problem solved after the freeze reports no
	// pending attempts, because attempts stop counting once a problem is solved.
	Pending       uint32 `protobuf:"varint,7,opt,name=pending,proto3" json:"pending,omitempty"`
	Changed       bool   `protobuf:"varint,8,opt,name=changed,proto3" json:"changed,omitempty"`
	FirstToSolve  bool   `protobuf:"varint,9,opt,name=first_to_solve,json=firstToSolve,proto3" json:"first_to_solve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row_ProblemScore) Reset() {
	*x = Row_ProblemScore{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row_ProblemScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row_ProblemScore) ProtoMessage() {}

func (x *Row_ProblemScore) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row_ProblemScore.ProtoReflect.Descriptor instead.
func (*Row_ProblemScore) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Row_ProblemScore) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Row_ProblemScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Row_ProblemScore) GetPenalty() float32 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *Row_ProblemScore) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Row_ProblemScore) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Row_ProblemScore) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Row_ProblemScore) GetPending() uint32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *Row_ProblemScore) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *Row_ProblemScore) GetFirstToSolve() bool {
	if x != nil {
		return x.FirstToSolve
	}
	return false
}

type Row_ContestScore struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ContestId string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Score     float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Penalty   float32                `protobuf:"fixed32,3,opt,name=penalty,proto3" json:"penalty,omitempty"`
	// False when best_of leaves this contest out of the total. The score is still reported, for display.
	Counted       bool                `protobuf:"varint,4,opt,name=counted,proto3" json:"counted,omitempty"`
	Frozen        bool                `protobuf:"varint,5,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Problems      []*Row_ProblemScore `protobuf:"bytes,20,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row_ContestScore) Reset() {
	*x = Row_ContestScore{}
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row_ContestScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row_ContestScore) ProtoMessage() {}

func (x *Row_ContestScore) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_scoreboard_scoreboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row_ContestScore.ProtoReflect.Descriptor instead.
func (*Row_ContestScore) Descriptor() ([]byte, []int) {
	return file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Row_ContestScore) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *Row_ContestScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Row_ContestScore) GetPenalty() float32 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *Row_ContestScore) GetCounted() bool {
	if x != nil {
		return x.Counted
	}
	return false
}

func (x *Row_ContestScore) GetFrozen() bool {
	if x != nil {
		return x.Frozen
	}
	return false
}

func (x *Row_ContestScore) GetProblems() []*Row_ProblemScore {
	if x != nil {
		return x.Problems
	}
	return nil
}

var File_eolymp_scoreboard_scoreboard_proto protoreflect.FileDescriptor

const file_eolymp_scoreboard_scoreboard_proto_rawDesc = "" +
	"\n" +
	"\"eolymp/scoreboard/scoreboard.proto\x12\x11eolymp.scoreboard\"\x99\x05\n" +
	"\n" +
	"Scoreboard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\abest_of\x18\x04 \x01(\rR\x06bestOf\x128\n" +
	"\x05modes\x18\a \x03(\x0e2\".eolymp.scoreboard.Scoreboard.ModeR\x05modes\x12A\n" +
	"\bcontests\x18\n" +
	" \x03(\v2%.eolymp.scoreboard.Scoreboard.ContestR\bcontests\x1a\xb2\x01\n" +
	"\aContest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\v \x01(\tR\bimageUrl\x12A\n" +
	"\bproblems\x18\x14 \x03(\v2%.eolymp.scoreboard.Scoreboard.ProblemR\bproblems\x1aT\n" +
	"\aProblem\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\tR\tproblemId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x1au\n" +
	"\x05Patch\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slug\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1c\n" +
	"\abest_of\x18\x04 \x01(\rH\x02R\x06bestOf\x88\x01\x01B\a\n" +
	"\x05_slugB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_best_of\";\n" +
	"\x04Mode\x12\x10\n" +
	"\fUNKNOWN_MODE\x10\x00\x12\b\n" +
	"\x04MAIN\x10\x01\x12\n" +
	"\n" +
	"\x06FROZEN\x10\x02\x12\v\n" +
	"\aUPSOLVE\x10\x03\"\xe5\x06\n" +
	"\x03Row\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05index\x18\n" +
	" \x01(\rR\x05index\x12\x12\n" +
	"\x04rank\x18\v \x01(\rR\x04rank\x12\x1f\n" +
	"\vrank_length\x18\f \x01(\rR\n" +
	"rankLength\x12\x19\n" +
	"\brank_all\x18\r \x01(\rR\arankAll\x12&\n" +
	"\x0frank_all_length\x18\x0e \x01(\rR\rrankAllLength\x12\x14\n" +
	"\x05score\x18\x14 \x01(\x02R\x05score\x12\x18\n" +
	"\apenalty\x18\x15 \x01(\x02R\apenalty\x12\x1e\n" +
	"\n" +
	"unofficial\x18\x1e \x01(\bR\n" +
	"unofficial\x12\"\n" +
	"\fdisqualified\x18\x1f \x01(\bR\fdisqualified\x12?\n" +
	"\bcontests\x182 \x03(\v2#.eolymp.scoreboard.Row.ContestScoreR\bcontests\x1a\x87\x02\n" +
	"\fProblemScore\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\tR\tproblemId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x18\n" +
	"\apenalty\x18\x03 \x01(\x02R\apenalty\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentage\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\rR\battempts\x12\x12\n" +
	"\x04time\x18\x06 \x01(\rR\x04time\x12\x18\n" +
	"\apending\x18\a \x01(\rR\apending\x12\x18\n" +
	"\achanged\x18\b \x01(\bR\achanged\x12$\n" +
	"\x0efirst_to_solve\x18\t \x01(\bR\ffirstToSolve\x1a\xd0\x01\n" +
	"\fContestScore\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x18\n" +
	"\apenalty\x18\x03 \x01(\x02R\apenalty\x12\x18\n" +
	"\acounted\x18\x04 \x01(\bR\acounted\x12\x16\n" +
	"\x06frozen\x18\x05 \x01(\bR\x06frozen\x12?\n" +
	"\bproblems\x18\x14 \x03(\v2#.eolymp.scoreboard.Row.ProblemScoreR\bproblemsB7Z5github.com/eolymp/go-sdk/eolymp/scoreboard;scoreboardb\x06proto3"

var (
	file_eolymp_scoreboard_scoreboard_proto_rawDescOnce sync.Once
	file_eolymp_scoreboard_scoreboard_proto_rawDescData []byte
)

func file_eolymp_scoreboard_scoreboard_proto_rawDescGZIP() []byte {
	file_eolymp_scoreboard_scoreboard_proto_rawDescOnce.Do(func() {
		file_eolymp_scoreboard_scoreboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eolymp_scoreboard_scoreboard_proto_rawDesc), len(file_eolymp_scoreboard_scoreboard_proto_rawDesc)))
	})
	return file_eolymp_scoreboard_scoreboard_proto_rawDescData
}

var file_eolymp_scoreboard_scoreboard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eolymp_scoreboard_scoreboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_eolymp_scoreboard_scoreboard_proto_goTypes = []any{
	(Scoreboard_Mode)(0),       // 0: eolymp.scoreboard.Scoreboard.Mode
	(*Scoreboard)(nil),         // 1: eolymp.scoreboard.Scoreboard
	(*Row)(nil),                // 2: eolymp.scoreboard.Row
	(*Scoreboard_Contest)(nil), // 3: eolymp.scoreboard.Scoreboard.Contest
	(*Scoreboard_Problem)(nil), // 4: eolymp.scoreboard.Scoreboard.Problem
	(*Scoreboard_Patch)(nil),   // 5: eolymp.scoreboard.Scoreboard.Patch
	(*Row_ProblemScore)(nil),   // 6: eolymp.scoreboard.Row.ProblemScore
	(*Row_ContestScore)(nil),   // 7: eolymp.scoreboard.Row.ContestScore
}
var file_eolymp_scoreboard_scoreboard_proto_depIdxs = []int32{
	0, // 0: eolymp.scoreboard.Scoreboard.modes:type_name -> eolymp.scoreboard.Scoreboard.Mode
	3, // 1: eolymp.scoreboard.Scoreboard.contests:type_name -> eolymp.scoreboard.Scoreboard.Contest
	7, // 2: eolymp.scoreboard.Row.contests:type_name -> eolymp.scoreboard.Row.ContestScore
	4, // 3: eolymp.scoreboard.Scoreboard.Contest.problems:type_name -> eolymp.scoreboard.Scoreboard.Problem
	6, // 4: eolymp.scoreboard.Row.ContestScore.problems:type_name -> eolymp.scoreboard.Row.ProblemScore
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_eolymp_scoreboard_scoreboard_proto_init() }
func file_eolymp_scoreboard_scoreboard_proto_init() {
	if File_eolymp_scoreboard_scoreboard_proto != nil {
		return
	}
	file_eolymp_scoreboard_scoreboard_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eolymp_scoreboard_scoreboard_proto_rawDesc), len(file_eolymp_scoreboard_scoreboard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eolymp_scoreboard_scoreboard_proto_goTypes,
		DependencyIndexes: file_eolymp_scoreboard_scoreboard_proto_depIdxs,
		EnumInfos:         file_eolymp_scoreboard_scoreboard_proto_enumTypes,
		MessageInfos:      file_eolymp_scoreboard_scoreboard_proto_msgTypes,
	}.Build()
	File_eolymp_scoreboard_scoreboard_proto = out.File
	file_eolymp_scoreboard_scoreboard_proto_goTypes = nil
	file_eolymp_scoreboard_scoreboard_proto_depIdxs = nil
}
