// Code generated by protoc-gen-go-server. DO NOT EDIT.
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-go-server for more details.

package acl

import (
	errors "errors"
	go_querystring "github.com/eolymp/go-querystring"
	mux "github.com/gorilla/mux"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	metadata "google.golang.org/grpc/metadata"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	io "io"
	http "net/http"
	url "net/url"
	strconv "strconv"
)

var errPrincipalServiceRequestTooLarge = errors.New("request too large")

// _PrincipalService_HTTPReadQueryString parses query string into proto.Message with size limit
func _PrincipalService_HTTPReadQueryString(r *http.Request, v proto.Message, maxSize int64) error {
	if int64(len(r.URL.RawQuery)) > maxSize {
		return errPrincipalServiceRequestTooLarge
	}

	if h := r.Header.Values("Strict-Parsing"); len(h) > 0 {
		strict, err := strconv.ParseBool(h[len(h)-1])
		if err != nil {
			return err
		}

		if strict {
			query, err := url.ParseQuery(r.URL.RawQuery)
			if err != nil {
				return err
			}

			return go_querystring.UnmarshalStrict(query, v)
		}
	}

	return go_querystring.Unmarshal(r.URL.Query(), v)
}

// _PrincipalService_HTTPReadRequestBody parses body into proto.Message with size limit
func _PrincipalService_HTTPReadRequestBody(r *http.Request, v proto.Message, maxSize int64) error {
	data, err := io.ReadAll(http.MaxBytesReader(nil, r.Body, maxSize))
	if err != nil {
		if err.Error() == "http: request body too large" {
			return errPrincipalServiceRequestTooLarge
		}
		return err
	}

	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, v)); err != nil {
		return err
	}

	return nil
}

// _PrincipalService_HTTPWriteResponse writes proto.Message to HTTP response
func _PrincipalService_HTTPWriteResponse(w http.ResponseWriter, v proto.Message, h, t metadata.MD) {
	data, err := protojson.Marshal(v)
	if err != nil {
		_PrincipalService_HTTPWriteErrorResponse(w, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")

	if v := append(h.Get("cache-control"), t.Get("cache-control")...); len(v) > 0 {
		w.Header().Set("Cache-Control", v[len(v)-1])
	}

	if v := append(h.Get("etag"), t.Get("etag")...); len(v) > 0 {
		w.Header().Set("ETag", v[len(v)-1])
	}

	if v := append(h.Get("last-modified"), t.Get("last-modified")...); len(v) > 0 {
		w.Header().Set("Last-Modified", v[len(v)-1])
	}

	w.WriteHeader(http.StatusOK)

	_, _ = w.Write(data)
}

// _PrincipalService_HTTPWriteErrorResponse writes error to HTTP response with error status code
func _PrincipalService_HTTPWriteErrorResponse(w http.ResponseWriter, e error) {
	s := status.Convert(e)

	if e == errPrincipalServiceRequestTooLarge {
		w.WriteHeader(http.StatusRequestEntityTooLarge)
		_, _ = w.Write([]byte("request too large"))
		return
	}

	w.Header().Set("Content-Type", "application/json")

	switch s.Code() {
	case codes.OK:
		w.WriteHeader(http.StatusOK)
	case codes.Canceled:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.Unknown:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.InvalidArgument:
		w.WriteHeader(http.StatusBadRequest)
	case codes.DeadlineExceeded:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.NotFound:
		w.WriteHeader(http.StatusNotFound)
	case codes.AlreadyExists:
		w.WriteHeader(http.StatusConflict)
	case codes.PermissionDenied:
		w.WriteHeader(http.StatusForbidden)
	case codes.ResourceExhausted:
		w.WriteHeader(http.StatusTooManyRequests)
	case codes.FailedPrecondition:
		w.WriteHeader(http.StatusPreconditionFailed)
	case codes.Aborted:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.OutOfRange:
		w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
	case codes.Unimplemented:
		w.WriteHeader(http.StatusNotImplemented)
	case codes.Internal:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unavailable:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.DataLoss:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unauthenticated:
		w.WriteHeader(http.StatusUnauthorized)
	default:
		w.WriteHeader(http.StatusInternalServerError)
	}

	data, err := protojson.Marshal(s.Proto())
	if err != nil {
		panic(err)
	}

	_, _ = w.Write(data)
}

// RegisterPrincipalServiceHttpHandlers adds handlers for for PrincipalServiceClient
func RegisterPrincipalServiceHttpHandlers(router *mux.Router, prefix string, cli PrincipalServiceClient) {
	router.Handle(prefix+"/principals", _PrincipalService_CreatePrincipal_Rule0(cli)).
		Methods("POST").
		Name("eolymp.acl.PrincipalService.CreatePrincipal")
	router.Handle(prefix+"/principals/{principal_id}", _PrincipalService_UpdatePrincipal_Rule0(cli)).
		Methods("PUT").
		Name("eolymp.acl.PrincipalService.UpdatePrincipal")
	router.Handle(prefix+"/principals/{principal_id}", _PrincipalService_DeletePrincipal_Rule0(cli)).
		Methods("DELETE").
		Name("eolymp.acl.PrincipalService.DeletePrincipal")
	router.Handle(prefix+"/principals/{principal_id}", _PrincipalService_DescribePrincipal_Rule0(cli)).
		Methods("GET").
		Name("eolymp.acl.PrincipalService.DescribePrincipal")
	router.Handle(prefix+"/principals", _PrincipalService_ListPrincipals_Rule0(cli)).
		Methods("GET").
		Name("eolymp.acl.PrincipalService.ListPrincipals")
}

// RegisterPrincipalServiceHttpProxy adds proxy handlers for for PrincipalServiceClient
func RegisterPrincipalServiceHttpProxy(router *mux.Router, prefix string, conn grpc.ClientConnInterface) {
	RegisterPrincipalServiceHttpHandlers(router, prefix, NewPrincipalServiceClient(conn))
}

func _PrincipalService_CreatePrincipal_Rule0(cli PrincipalServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &CreatePrincipalInput{}

		if err := _PrincipalService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		var header, trailer metadata.MD

		out, err := cli.CreatePrincipal(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		_PrincipalService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _PrincipalService_UpdatePrincipal_Rule0(cli PrincipalServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &UpdatePrincipalInput{}

		if err := _PrincipalService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.PrincipalId = vars["principal_id"]

		var header, trailer metadata.MD

		out, err := cli.UpdatePrincipal(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		_PrincipalService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _PrincipalService_DeletePrincipal_Rule0(cli PrincipalServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DeletePrincipalInput{}

		if err := _PrincipalService_HTTPReadRequestBody(r, in, 1048576); err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.PrincipalId = vars["principal_id"]

		var header, trailer metadata.MD

		out, err := cli.DeletePrincipal(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		_PrincipalService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _PrincipalService_DescribePrincipal_Rule0(cli PrincipalServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribePrincipalInput{}

		if err := _PrincipalService_HTTPReadQueryString(r, in, 131072); err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.PrincipalId = vars["principal_id"]

		var header, trailer metadata.MD

		out, err := cli.DescribePrincipal(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		_PrincipalService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _PrincipalService_ListPrincipals_Rule0(cli PrincipalServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListPrincipalsInput{}

		if err := _PrincipalService_HTTPReadQueryString(r, in, 131072); err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		var header, trailer metadata.MD

		out, err := cli.ListPrincipals(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_PrincipalService_HTTPWriteErrorResponse(w, err)
			return
		}

		_PrincipalService_HTTPWriteResponse(w, out, header, trailer)
	})
}
