// Code generated by protoc-gen-go-server. DO NOT EDIT.
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-go-server for more details.

package ranker

import (
	context "context"
	oauth "github.com/eolymp/go-packages/oauth"
	mux "github.com/gorilla/mux"
	prometheus "github.com/prometheus/client_golang/prometheus"
	promauto "github.com/prometheus/client_golang/prometheus/promauto"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	ioutil "io/ioutil"
	http "net/http"
	time "time"
)

// _Ranker_HTTPReadQueryString parses body into proto.Message
func _Ranker_HTTPReadQueryString(r *http.Request, v proto.Message) error {
	query := r.URL.Query().Get("q")
	if query == "" {
		return nil
	}

	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal([]byte(query), v)); err != nil {
		return err
	}

	return nil
}

// _Ranker_HTTPReadRequestBody parses body into proto.Message
func _Ranker_HTTPReadRequestBody(r *http.Request, v proto.Message) error {
	data, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return err
	}

	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, v)); err != nil {
		return err
	}

	return nil
}

// _Ranker_HTTPWriteResponse writes proto.Message to HTTP response
func _Ranker_HTTPWriteResponse(w http.ResponseWriter, v proto.Message) {
	data, err := protojson.Marshal(v)
	if err != nil {
		_Ranker_HTTPWriteErrorResponse(w, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	_, _ = w.Write(data)
}

// _Ranker_HTTPWriteErrorResponse writes error to HTTP response with error status code
func _Ranker_HTTPWriteErrorResponse(w http.ResponseWriter, e error) {
	s := status.Convert(e)

	w.Header().Set("Content-Type", "application/json")

	switch s.Code() {
	case codes.OK:
		w.WriteHeader(http.StatusOK)
	case codes.Canceled:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.Unknown:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.InvalidArgument:
		w.WriteHeader(http.StatusBadRequest)
	case codes.DeadlineExceeded:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.NotFound:
		w.WriteHeader(http.StatusNotFound)
	case codes.AlreadyExists:
		w.WriteHeader(http.StatusConflict)
	case codes.PermissionDenied:
		w.WriteHeader(http.StatusForbidden)
	case codes.ResourceExhausted:
		w.WriteHeader(http.StatusTooManyRequests)
	case codes.FailedPrecondition:
		w.WriteHeader(http.StatusPreconditionFailed)
	case codes.Aborted:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.OutOfRange:
		w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
	case codes.Unimplemented:
		w.WriteHeader(http.StatusNotImplemented)
	case codes.Internal:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unavailable:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.DataLoss:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unauthenticated:
		w.WriteHeader(http.StatusUnauthorized)
	default:
		w.WriteHeader(http.StatusInternalServerError)
	}

	data, err := protojson.Marshal(s.Proto())
	if err != nil {
		panic(err)
	}

	_, _ = w.Write(data)
}

// NewRankerHandler constructs new http.Handler for RankerServer
func NewRankerHandler(srv RankerServer) http.Handler {
	router := mux.NewRouter()
	router.Handle("/eolymp.ranker.Ranker/CreateScoreboard", _Ranker_CreateScoreboard(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/UpdateScoreboard", _Ranker_UpdateScoreboard(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/RebuildScoreboard", _Ranker_RebuildScoreboard(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/DeleteScoreboard", _Ranker_DeleteScoreboard(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/DescribeScoreboard", _Ranker_DescribeScoreboard(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/ListScoreboards", _Ranker_ListScoreboards(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/DescribeScoreboardRow", _Ranker_DescribeScoreboardRow(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/ListScoreboardRows", _Ranker_ListScoreboardRows(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/AddScoreboardColumn", _Ranker_AddScoreboardColumn(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/DeleteScoreboardColumn", _Ranker_DeleteScoreboardColumn(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/DescribeScoreboardColumn", _Ranker_DescribeScoreboardColumn(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/ListScoreboardColumns", _Ranker_ListScoreboardColumns(srv)).Methods(http.MethodPost)
	router.Handle("/eolymp.ranker.Ranker/ListActivities", _Ranker_ListActivities(srv)).Methods(http.MethodPost)
	return router
}

// NewRankerHandlerHttp constructs new http.Handler for RankerServer
// This constructor creates http.Handler, the actual implementation might change at any moment
func NewRankerHandlerHttp(srv RankerServer, prefix string) http.Handler {
	router := mux.NewRouter()

	router.Handle(prefix+"/scoreboards", _Ranker_CreateScoreboard_Rule0(srv)).
		Methods("POST").
		Name("eolymp.ranker.Ranker.CreateScoreboard")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}", _Ranker_UpdateScoreboard_Rule0(srv)).
		Methods("PUT").
		Name("eolymp.ranker.Ranker.UpdateScoreboard")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/rebuild", _Ranker_RebuildScoreboard_Rule0(srv)).
		Methods("POST").
		Name("eolymp.ranker.Ranker.RebuildScoreboard")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}", _Ranker_DeleteScoreboard_Rule0(srv)).
		Methods("DELETE").
		Name("eolymp.ranker.Ranker.DeleteScoreboard")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}", _Ranker_DescribeScoreboard_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.DescribeScoreboard")

	router.Handle(prefix+"/scoreboards", _Ranker_ListScoreboards_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.ListScoreboards")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/rows/{member_id}", _Ranker_DescribeScoreboardRow_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.DescribeScoreboardRow")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/rows", _Ranker_ListScoreboardRows_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.ListScoreboardRows")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/columns", _Ranker_AddScoreboardColumn_Rule0(srv)).
		Methods("POST").
		Name("eolymp.ranker.Ranker.AddScoreboardColumn")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/columns/{column_id}", _Ranker_DeleteScoreboardColumn_Rule0(srv)).
		Methods("DELETE").
		Name("eolymp.ranker.Ranker.DeleteScoreboardColumn")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/columns/{column_id}", _Ranker_DescribeScoreboardColumn_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.DescribeScoreboardColumn")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/columns", _Ranker_ListScoreboardColumns_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.ListScoreboardColumns")

	router.Handle(prefix+"/scoreboards/{scoreboard_id}/activities", _Ranker_ListActivities_Rule0(srv)).
		Methods("GET").
		Name("eolymp.ranker.Ranker.ListActivities")

	return router
}

func _Ranker_CreateScoreboard(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &CreateScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.CreateScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_UpdateScoreboard(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &UpdateScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.UpdateScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_RebuildScoreboard(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &RebuildScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.RebuildScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DeleteScoreboard(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DeleteScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.DeleteScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DescribeScoreboard(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.DescribeScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListScoreboards(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListScoreboardsInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.ListScoreboards(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DescribeScoreboardRow(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeScoreboardRowInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.DescribeScoreboardRow(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListScoreboardRows(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListScoreboardRowsInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.ListScoreboardRows(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_AddScoreboardColumn(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &AddScoreboardColumnInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.AddScoreboardColumn(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DeleteScoreboardColumn(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DeleteScoreboardColumnInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.DeleteScoreboardColumn(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DescribeScoreboardColumn(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeScoreboardColumnInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.DescribeScoreboardColumn(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListScoreboardColumns(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListScoreboardColumnsInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.ListScoreboardColumns(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListActivities(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListActivitiesInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.ListActivities(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_CreateScoreboard_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &CreateScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.CreateScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_UpdateScoreboard_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &UpdateScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.UpdateScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_RebuildScoreboard_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &RebuildScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.RebuildScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DeleteScoreboard_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DeleteScoreboardInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.DeleteScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DescribeScoreboard_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeScoreboardInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.DescribeScoreboard(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListScoreboards_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListScoreboardsInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		out, err := srv.ListScoreboards(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DescribeScoreboardRow_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeScoreboardRowInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]
		in.MemberId = vars["member_id"]

		out, err := srv.DescribeScoreboardRow(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListScoreboardRows_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListScoreboardRowsInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.ListScoreboardRows(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_AddScoreboardColumn_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &AddScoreboardColumnInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.AddScoreboardColumn(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DeleteScoreboardColumn_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DeleteScoreboardColumnInput{}

		if err := _Ranker_HTTPReadRequestBody(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]
		in.ColumnId = vars["column_id"]

		out, err := srv.DeleteScoreboardColumn(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_DescribeScoreboardColumn_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeScoreboardColumnInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]
		in.ColumnId = vars["column_id"]

		out, err := srv.DescribeScoreboardColumn(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListScoreboardColumns_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListScoreboardColumnsInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.ListScoreboardColumns(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

func _Ranker_ListActivities_Rule0(srv RankerServer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListActivitiesInput{}

		if err := _Ranker_HTTPReadQueryString(r, in); err != nil {
			err = status.New(codes.InvalidArgument, err.Error()).Err()
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.ScoreboardId = vars["scoreboard_id"]

		out, err := srv.ListActivities(r.Context(), in)
		if err != nil {
			_Ranker_HTTPWriteErrorResponse(w, err)
			return
		}

		_Ranker_HTTPWriteResponse(w, out)
	})
}

var promRankerRequestLatency = promauto.NewHistogramVec(prometheus.HistogramOpts{
	Name:    "ranker_request_latency",
	Help:    "Ranker request latency",
	Buckets: []float64{0.1, 0.4, 1, 5},
}, []string{"method", "status"})

type _RankerLimiter interface {
	Allow(context.Context, string, float64, int) bool
}

type RankerInterceptor struct {
	limiter _RankerLimiter
	server  RankerServer
}

// NewRankerInterceptor constructs additional middleware for a server based on annotations in proto files
func NewRankerInterceptor(srv RankerServer, lim _RankerLimiter) *RankerInterceptor {
	return &RankerInterceptor{server: srv, limiter: lim}
}

func (i *RankerInterceptor) CreateScoreboard(ctx context.Context, in *CreateScoreboardInput) (out *CreateScoreboardOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/CreateScoreboard", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:write") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:write")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/CreateScoreboard", 1, 5) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.CreateScoreboard(ctx, in)
	return
}

func (i *RankerInterceptor) UpdateScoreboard(ctx context.Context, in *UpdateScoreboardInput) (out *UpdateScoreboardOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/UpdateScoreboard", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:write") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:write")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/UpdateScoreboard", 1, 5) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.UpdateScoreboard(ctx, in)
	return
}

func (i *RankerInterceptor) RebuildScoreboard(ctx context.Context, in *RebuildScoreboardInput) (out *RebuildScoreboardOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/RebuildScoreboard", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:write") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:write")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/RebuildScoreboard", 1, 5) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.RebuildScoreboard(ctx, in)
	return
}

func (i *RankerInterceptor) DeleteScoreboard(ctx context.Context, in *DeleteScoreboardInput) (out *DeleteScoreboardOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/DeleteScoreboard", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:write") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:write")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/DeleteScoreboard", 2, 10) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.DeleteScoreboard(ctx, in)
	return
}

func (i *RankerInterceptor) DescribeScoreboard(ctx context.Context, in *DescribeScoreboardInput) (out *DescribeScoreboardOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/DescribeScoreboard", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/DescribeScoreboard", 5, 20) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.DescribeScoreboard(ctx, in)
	return
}

func (i *RankerInterceptor) ListScoreboards(ctx context.Context, in *ListScoreboardsInput) (out *ListScoreboardsOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/ListScoreboards", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/ListScoreboards", 5, 20) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.ListScoreboards(ctx, in)
	return
}

func (i *RankerInterceptor) DescribeScoreboardRow(ctx context.Context, in *DescribeScoreboardRowInput) (out *DescribeScoreboardRowOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/DescribeScoreboardRow", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/DescribeScoreboardRow", 10, 100) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.DescribeScoreboardRow(ctx, in)
	return
}

func (i *RankerInterceptor) ListScoreboardRows(ctx context.Context, in *ListScoreboardRowsInput) (out *ListScoreboardRowsOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/ListScoreboardRows", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/ListScoreboardRows", 10, 100) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.ListScoreboardRows(ctx, in)
	return
}

func (i *RankerInterceptor) AddScoreboardColumn(ctx context.Context, in *AddScoreboardColumnInput) (out *AddScoreboardColumnOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/AddScoreboardColumn", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:write") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:write")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/AddScoreboardColumn", 1, 5) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.AddScoreboardColumn(ctx, in)
	return
}

func (i *RankerInterceptor) DeleteScoreboardColumn(ctx context.Context, in *DeleteScoreboardColumnInput) (out *DeleteScoreboardColumnOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/DeleteScoreboardColumn", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:write") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:write")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/DeleteScoreboardColumn", 1, 5) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.DeleteScoreboardColumn(ctx, in)
	return
}

func (i *RankerInterceptor) DescribeScoreboardColumn(ctx context.Context, in *DescribeScoreboardColumnInput) (out *DescribeScoreboardColumnOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/DescribeScoreboardColumn", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/DescribeScoreboardColumn", 10, 100) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.DescribeScoreboardColumn(ctx, in)
	return
}

func (i *RankerInterceptor) ListScoreboardColumns(ctx context.Context, in *ListScoreboardColumnsInput) (out *ListScoreboardColumnsOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/ListScoreboardColumns", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("ranker:scoreboard:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: ranker:scoreboard:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/ListScoreboardColumns", 10, 100) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.ListScoreboardColumns(ctx, in)
	return
}

func (i *RankerInterceptor) ListActivities(ctx context.Context, in *ListActivitiesInput) (out *ListActivitiesOutput, err error) {
	start := time.Now()
	defer func() {
		s, _ := status.FromError(err)
		if s == nil {
			s = status.New(codes.OK, "OK")
		}

		promRankerRequestLatency.WithLabelValues("eolymp.ranker.Ranker/ListActivities", s.Code().String()).
			Observe(time.Since(start).Seconds())
	}()

	token, ok := oauth.TokenFromContext(ctx)
	if ok && !token.Has("judge:contest:read") {
		err = status.Error(codes.PermissionDenied, "required token scopes are missing: judge:contest:read")
		return
	}

	if !i.limiter.Allow(ctx, "eolymp.ranker.Ranker/ListActivities", 5, 20) {
		err = status.Error(codes.ResourceExhausted, "too many requests")
		return
	}

	out, err = i.server.ListActivities(ctx, in)
	return
}
