// Code generated by protoc-gen-go-server. DO NOT EDIT.
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-go-server for more details.

package certificate

import (
	go_querystring "github.com/eolymp/go-querystring"
	mux "github.com/gorilla/mux"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	metadata "google.golang.org/grpc/metadata"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	ioutil "io/ioutil"
	http "net/http"
	url "net/url"
	strconv "strconv"
)

// _CertificateService_HTTPReadQueryString parses body into proto.Message
func _CertificateService_HTTPReadQueryString(r *http.Request, v proto.Message) error {
	if h := r.Header.Values("Strict-Parsing"); len(h) > 0 {
		strict, err := strconv.ParseBool(h[len(h)-1])
		if err != nil {
			return err
		}

		if strict {
			query, err := url.ParseQuery(r.URL.RawQuery)
			if err != nil {
				return err
			}

			return go_querystring.UnmarshalStrict(query, v)
		}
	}

	return go_querystring.Unmarshal(r.URL.Query(), v)
}

// _CertificateService_HTTPReadRequestBody parses body into proto.Message
func _CertificateService_HTTPReadRequestBody(r *http.Request, v proto.Message) error {
	data, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return err
	}

	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, v)); err != nil {
		return err
	}

	return nil
}

// _CertificateService_HTTPWriteResponse writes proto.Message to HTTP response
func _CertificateService_HTTPWriteResponse(w http.ResponseWriter, v proto.Message, h, t metadata.MD) {
	data, err := protojson.Marshal(v)
	if err != nil {
		_CertificateService_HTTPWriteErrorResponse(w, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")

	if v := append(h.Get("cache-control"), t.Get("cache-control")...); len(v) > 0 {
		w.Header().Set("Cache-Control", v[len(v)-1])
	}

	if v := append(h.Get("etag"), t.Get("etag")...); len(v) > 0 {
		w.Header().Set("ETag", v[len(v)-1])
	}

	if v := append(h.Get("last-modified"), t.Get("last-modified")...); len(v) > 0 {
		w.Header().Set("Last-Modified", v[len(v)-1])
	}

	w.WriteHeader(http.StatusOK)

	_, _ = w.Write(data)
}

// _CertificateService_HTTPWriteErrorResponse writes error to HTTP response with error status code
func _CertificateService_HTTPWriteErrorResponse(w http.ResponseWriter, e error) {
	s := status.Convert(e)

	w.Header().Set("Content-Type", "application/json")

	switch s.Code() {
	case codes.OK:
		w.WriteHeader(http.StatusOK)
	case codes.Canceled:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.Unknown:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.InvalidArgument:
		w.WriteHeader(http.StatusBadRequest)
	case codes.DeadlineExceeded:
		w.WriteHeader(http.StatusGatewayTimeout)
	case codes.NotFound:
		w.WriteHeader(http.StatusNotFound)
	case codes.AlreadyExists:
		w.WriteHeader(http.StatusConflict)
	case codes.PermissionDenied:
		w.WriteHeader(http.StatusForbidden)
	case codes.ResourceExhausted:
		w.WriteHeader(http.StatusTooManyRequests)
	case codes.FailedPrecondition:
		w.WriteHeader(http.StatusPreconditionFailed)
	case codes.Aborted:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.OutOfRange:
		w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
	case codes.Unimplemented:
		w.WriteHeader(http.StatusNotImplemented)
	case codes.Internal:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unavailable:
		w.WriteHeader(http.StatusServiceUnavailable)
	case codes.DataLoss:
		w.WriteHeader(http.StatusInternalServerError)
	case codes.Unauthenticated:
		w.WriteHeader(http.StatusUnauthorized)
	default:
		w.WriteHeader(http.StatusInternalServerError)
	}

	data, err := protojson.Marshal(s.Proto())
	if err != nil {
		panic(err)
	}

	_, _ = w.Write(data)
}

// RegisterCertificateServiceHttpHandlers adds handlers for for CertificateServiceClient
func RegisterCertificateServiceHttpHandlers(router *mux.Router, prefix string, cli CertificateServiceClient) {
	router.Handle(prefix+"/certificates", _CertificateService_CreateCertificate_Rule0(cli)).
		Methods("POST").
		Name("eolymp.certificate.CertificateService.CreateCertificate")
	router.Handle(prefix+"/certificates/{certificate_id}", _CertificateService_VoidCertificate_Rule0(cli)).
		Methods("DELETE").
		Name("eolymp.certificate.CertificateService.VoidCertificate")
	router.Handle(prefix+"/certificates/{certificate_id}", _CertificateService_DescribeCertificate_Rule0(cli)).
		Methods("GET").
		Name("eolymp.certificate.CertificateService.DescribeCertificate")
	router.Handle(prefix+"/members/{member_id}/certificates", _CertificateService_ListCertificates_Rule0(cli)).
		Methods("GET").
		Name("eolymp.certificate.CertificateService.ListCertificates")
}

// RegisterCertificateServiceHttpProxy adds proxy handlers for for CertificateServiceClient
func RegisterCertificateServiceHttpProxy(router *mux.Router, prefix string, conn grpc.ClientConnInterface) {
	RegisterCertificateServiceHttpHandlers(router, prefix, NewCertificateServiceClient(conn))
}

func _CertificateService_CreateCertificate_Rule0(cli CertificateServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &CreateCertificateInput{}

		if err := _CertificateService_HTTPReadRequestBody(r, in); err != nil {
			err = status.Error(codes.InvalidArgument, err.Error())
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		var header, trailer metadata.MD

		out, err := cli.CreateCertificate(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		_CertificateService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _CertificateService_VoidCertificate_Rule0(cli CertificateServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &VoidCertificateInput{}

		if err := _CertificateService_HTTPReadRequestBody(r, in); err != nil {
			err = status.Error(codes.InvalidArgument, err.Error())
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.CertificateId = vars["certificate_id"]

		var header, trailer metadata.MD

		out, err := cli.VoidCertificate(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		_CertificateService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _CertificateService_DescribeCertificate_Rule0(cli CertificateServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &DescribeCertificateInput{}

		if err := _CertificateService_HTTPReadQueryString(r, in); err != nil {
			err = status.Error(codes.InvalidArgument, err.Error())
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.CertificateId = vars["certificate_id"]

		var header, trailer metadata.MD

		out, err := cli.DescribeCertificate(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		_CertificateService_HTTPWriteResponse(w, out, header, trailer)
	})
}

func _CertificateService_ListCertificates_Rule0(cli CertificateServiceClient) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		in := &ListCertificatesInput{}

		if err := _CertificateService_HTTPReadQueryString(r, in); err != nil {
			err = status.Error(codes.InvalidArgument, err.Error())
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		vars := mux.Vars(r)
		in.MemberId = vars["member_id"]

		var header, trailer metadata.MD

		out, err := cli.ListCertificates(r.Context(), in, grpc.Header(&header), grpc.Trailer(&trailer))
		if err != nil {
			_CertificateService_HTTPWriteErrorResponse(w, err)
			return
		}

		_CertificateService_HTTPWriteResponse(w, out, header, trailer)
	})
}
