// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: eolymp/atlas/stress_service.proto

package atlas

import (
	_ "github.com/eolymp/go-sdk/eolymp/annotations"
	wellknown "github.com/eolymp/go-sdk/eolymp/wellknown"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunStressInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Stress        *Stress                `protobuf:"bytes,1,opt,name=stress,proto3" json:"stress,omitempty"` // required; only the configuration fields are read
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStressInput) Reset() {
	*x = RunStressInput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStressInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStressInput) ProtoMessage() {}

func (x *RunStressInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStressInput.ProtoReflect.Descriptor instead.
func (*RunStressInput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{0}
}

func (x *RunStressInput) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *RunStressInput) GetStress() *Stress {
	if x != nil {
		return x.Stress
	}
	return nil
}

type RunStressOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StressId      string                 `protobuf:"bytes,1,opt,name=stress_id,json=stressId,proto3" json:"stress_id,omitempty"`
	Stress        *Stress                `protobuf:"bytes,2,opt,name=stress,proto3" json:"stress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStressOutput) Reset() {
	*x = RunStressOutput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStressOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStressOutput) ProtoMessage() {}

func (x *RunStressOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStressOutput.ProtoReflect.Descriptor instead.
func (*RunStressOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{1}
}

func (x *RunStressOutput) GetStressId() string {
	if x != nil {
		return x.StressId
	}
	return ""
}

func (x *RunStressOutput) GetStress() *Stress {
	if x != nil {
		return x.Stress
	}
	return nil
}

type DescribeStressInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	StressId      string                 `protobuf:"bytes,1,opt,name=stress_id,json=stressId,proto3" json:"stress_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeStressInput) Reset() {
	*x = DescribeStressInput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeStressInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeStressInput) ProtoMessage() {}

func (x *DescribeStressInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeStressInput.ProtoReflect.Descriptor instead.
func (*DescribeStressInput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeStressInput) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *DescribeStressInput) GetStressId() string {
	if x != nil {
		return x.StressId
	}
	return ""
}

type DescribeStressOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stress        *Stress                `protobuf:"bytes,1,opt,name=stress,proto3" json:"stress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeStressOutput) Reset() {
	*x = DescribeStressOutput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeStressOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeStressOutput) ProtoMessage() {}

func (x *DescribeStressOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeStressOutput.ProtoReflect.Descriptor instead.
func (*DescribeStressOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeStressOutput) GetStress() *Stress {
	if x != nil {
		return x.Stress
	}
	return nil
}

type WatchStressInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	StressId      string                 `protobuf:"bytes,1,opt,name=stress_id,json=stressId,proto3" json:"stress_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStressInput) Reset() {
	*x = WatchStressInput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStressInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStressInput) ProtoMessage() {}

func (x *WatchStressInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStressInput.ProtoReflect.Descriptor instead.
func (*WatchStressInput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{4}
}

func (x *WatchStressInput) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *WatchStressInput) GetStressId() string {
	if x != nil {
		return x.StressId
	}
	return ""
}

type WatchStressOutput struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Event         wellknown.WatchEventType `protobuf:"varint,1,opt,name=event,proto3,enum=eolymp.wellknown.WatchEventType" json:"event,omitempty"`
	Stress        *Stress                  `protobuf:"bytes,2,opt,name=stress,proto3" json:"stress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStressOutput) Reset() {
	*x = WatchStressOutput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStressOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStressOutput) ProtoMessage() {}

func (x *WatchStressOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStressOutput.ProtoReflect.Descriptor instead.
func (*WatchStressOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{5}
}

func (x *WatchStressOutput) GetEvent() wellknown.WatchEventType {
	if x != nil {
		return x.Event
	}
	return wellknown.WatchEventType(0)
}

func (x *WatchStressOutput) GetStress() *Stress {
	if x != nil {
		return x.Stress
	}
	return nil
}

type CancelStressInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	StressId      string                 `protobuf:"bytes,1,opt,name=stress_id,json=stressId,proto3" json:"stress_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStressInput) Reset() {
	*x = CancelStressInput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStressInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStressInput) ProtoMessage() {}

func (x *CancelStressInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStressInput.ProtoReflect.Descriptor instead.
func (*CancelStressInput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelStressInput) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *CancelStressInput) GetStressId() string {
	if x != nil {
		return x.StressId
	}
	return ""
}

type CancelStressOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStressOutput) Reset() {
	*x = CancelStressOutput{}
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStressOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStressOutput) ProtoMessage() {}

func (x *CancelStressOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_stress_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStressOutput.ProtoReflect.Descriptor instead.
func (*CancelStressOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_stress_service_proto_rawDescGZIP(), []int{7}
}

var File_eolymp_atlas_stress_service_proto protoreflect.FileDescriptor

const file_eolymp_atlas_stress_service_proto_rawDesc = "" +
	"\n" +
	"!eolymp/atlas/stress_service.proto\x12\feolymp.atlas\x1a\x1eeolymp/annotations/audit.proto\x1a\x1deolymp/annotations/http.proto\x1a\"eolymp/annotations/namespace.proto\x1a\"eolymp/annotations/ratelimit.proto\x1a\x1eeolymp/annotations/scope.proto\x1a\x19eolymp/atlas/stress.proto\x1a\x1ceolymp/wellknown/watch.proto\"]\n" +
	"\x0eRunStressInput\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12,\n" +
	"\x06stress\x18\x01 \x01(\v2\x14.eolymp.atlas.StressR\x06stress\"\\\n" +
	"\x0fRunStressOutput\x12\x1b\n" +
	"\tstress_id\x18\x01 \x01(\tR\bstressId\x12,\n" +
	"\x06stress\x18\x02 \x01(\v2\x14.eolymp.atlas.StressR\x06stress\"Q\n" +
	"\x13DescribeStressInput\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x1b\n" +
	"\tstress_id\x18\x01 \x01(\tR\bstressId\"D\n" +
	"\x14DescribeStressOutput\x12,\n" +
	"\x06stress\x18\x01 \x01(\v2\x14.eolymp.atlas.StressR\x06stress\"N\n" +
	"\x10WatchStressInput\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x1b\n" +
	"\tstress_id\x18\x01 \x01(\tR\bstressId\"y\n" +
	"\x11WatchStressOutput\x126\n" +
	"\x05event\x18\x01 \x01(\x0e2 .eolymp.wellknown.WatchEventTypeR\x05event\x12,\n" +
	"\x06stress\x18\x02 \x01(\v2\x14.eolymp.atlas.StressR\x06stress\"O\n" +
	"\x11CancelStressInput\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x1b\n" +
	"\tstress_id\x18\x01 \x01(\tR\bstressId\"\x14\n" +
	"\x12CancelStressOutput2\x93\x06\n" +
	"\rStressService\x12\xa3\x01\n" +
	"\tRunStress\x12\x1c.eolymp.atlas.RunStressInput\x1a\x1d.eolymp.atlas.RunStressOutput\"Y\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\x00?\xf8\xe2\n" +
	"\x05\x82\xe3\n" +
	"\x17\x8a\xe3\n" +
	"\x13atlas:problem:write\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x02\x82\xd3\xe4\x93\x02!\"\x1f/problems/{problem_id}/stresses\x12\xbd\x01\n" +
	"\x0eDescribeStress\x12!.eolymp.atlas.DescribeStressInput\x1a\".eolymp.atlas.DescribeStressOutput\"d\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00 A\xf8\xe2\n" +
	"2\x82\xe3\n" +
	"\x16\x8a\xe3\n" +
	"\x12atlas:problem:read\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x01\x82\xd3\xe4\x93\x02-\x12+/problems/{problem_id}/stresses/{stress_id}\x12\xbc\x01\n" +
	"\vWatchStress\x12\x1e.eolymp.atlas.WatchStressInput\x1a\x1f.eolymp.atlas.WatchStressOutput\"j\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\xa0@\xf8\xe2\n" +
	"\x14\x82\xe3\n" +
	"\x16\x8a\xe3\n" +
	"\x12atlas:problem:read\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x01\x82\xd3\xe4\x93\x023\x121/problems/{problem_id}/stresses/{stress_id}/watch0\x01\x12\xbf\x01\n" +
	"\fCancelStress\x12\x1f.eolymp.atlas.CancelStressInput\x1a .eolymp.atlas.CancelStressOutput\"l\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\x80?\xf8\xe2\n" +
	"\x05\x82\xe3\n" +
	"\x17\x8a\xe3\n" +
	"\x13atlas:problem:write\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x02\x82\xd3\xe4\x93\x024\"2/problems/{problem_id}/stresses/{stress_id}/cancel\x1a\x1b\x82\xf0\xf0\xe4\x01\x15eolymp.universe.SpaceB-Z+github.com/eolymp/go-sdk/eolymp/atlas;atlasb\x06proto3"

var (
	file_eolymp_atlas_stress_service_proto_rawDescOnce sync.Once
	file_eolymp_atlas_stress_service_proto_rawDescData []byte
)

func file_eolymp_atlas_stress_service_proto_rawDescGZIP() []byte {
	file_eolymp_atlas_stress_service_proto_rawDescOnce.Do(func() {
		file_eolymp_atlas_stress_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eolymp_atlas_stress_service_proto_rawDesc), len(file_eolymp_atlas_stress_service_proto_rawDesc)))
	})
	return file_eolymp_atlas_stress_service_proto_rawDescData
}

var file_eolymp_atlas_stress_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_eolymp_atlas_stress_service_proto_goTypes = []any{
	(*RunStressInput)(nil),        // 0: eolymp.atlas.RunStressInput
	(*RunStressOutput)(nil),       // 1: eolymp.atlas.RunStressOutput
	(*DescribeStressInput)(nil),   // 2: eolymp.atlas.DescribeStressInput
	(*DescribeStressOutput)(nil),  // 3: eolymp.atlas.DescribeStressOutput
	(*WatchStressInput)(nil),      // 4: eolymp.atlas.WatchStressInput
	(*WatchStressOutput)(nil),     // 5: eolymp.atlas.WatchStressOutput
	(*CancelStressInput)(nil),     // 6: eolymp.atlas.CancelStressInput
	(*CancelStressOutput)(nil),    // 7: eolymp.atlas.CancelStressOutput
	(*Stress)(nil),                // 8: eolymp.atlas.Stress
	(wellknown.WatchEventType)(0), // 9: eolymp.wellknown.WatchEventType
}
var file_eolymp_atlas_stress_service_proto_depIdxs = []int32{
	8, // 0: eolymp.atlas.RunStressInput.stress:type_name -> eolymp.atlas.Stress
	8, // 1: eolymp.atlas.RunStressOutput.stress:type_name -> eolymp.atlas.Stress
	8, // 2: eolymp.atlas.DescribeStressOutput.stress:type_name -> eolymp.atlas.Stress
	9, // 3: eolymp.atlas.WatchStressOutput.event:type_name -> eolymp.wellknown.WatchEventType
	8, // 4: eolymp.atlas.WatchStressOutput.stress:type_name -> eolymp.atlas.Stress
	0, // 5: eolymp.atlas.StressService.RunStress:input_type -> eolymp.atlas.RunStressInput
	2, // 6: eolymp.atlas.StressService.DescribeStress:input_type -> eolymp.atlas.DescribeStressInput
	4, // 7: eolymp.atlas.StressService.WatchStress:input_type -> eolymp.atlas.WatchStressInput
	6, // 8: eolymp.atlas.StressService.CancelStress:input_type -> eolymp.atlas.CancelStressInput
	1, // 9: eolymp.atlas.StressService.RunStress:output_type -> eolymp.atlas.RunStressOutput
	3, // 10: eolymp.atlas.StressService.DescribeStress:output_type -> eolymp.atlas.DescribeStressOutput
	5, // 11: eolymp.atlas.StressService.WatchStress:output_type -> eolymp.atlas.WatchStressOutput
	7, // 12: eolymp.atlas.StressService.CancelStress:output_type -> eolymp.atlas.CancelStressOutput
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_eolymp_atlas_stress_service_proto_init() }
func file_eolymp_atlas_stress_service_proto_init() {
	if File_eolymp_atlas_stress_service_proto != nil {
		return
	}
	file_eolymp_atlas_stress_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eolymp_atlas_stress_service_proto_rawDesc), len(file_eolymp_atlas_stress_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eolymp_atlas_stress_service_proto_goTypes,
		DependencyIndexes: file_eolymp_atlas_stress_service_proto_depIdxs,
		MessageInfos:      file_eolymp_atlas_stress_service_proto_msgTypes,
	}.Build()
	File_eolymp_atlas_stress_service_proto = out.File
	file_eolymp_atlas_stress_service_proto_goTypes = nil
	file_eolymp_atlas_stress_service_proto_depIdxs = nil
}
