// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: eolymp/atlas/topic.proto

package atlas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic_Extra int32

const (
	Topic_UNKNOWN_EXTRA Topic_Extra = 0
	Topic_VARIANTS      Topic_Extra = 1 // include topic translations
)

// Enum value maps for Topic_Extra.
var (
	Topic_Extra_name = map[int32]string{
		0: "UNKNOWN_EXTRA",
		1: "VARIANTS",
	}
	Topic_Extra_value = map[string]int32{
		"UNKNOWN_EXTRA": 0,
		"VARIANTS":      1,
	}
)

func (x Topic_Extra) Enum() *Topic_Extra {
	p := new(Topic_Extra)
	*p = x
	return p
}

func (x Topic_Extra) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Topic_Extra) Descriptor() protoreflect.EnumDescriptor {
	return file_eolymp_atlas_topic_proto_enumTypes[0].Descriptor()
}

func (Topic_Extra) Type() protoreflect.EnumType {
	return &file_eolymp_atlas_topic_proto_enumTypes[0]
}

func (x Topic_Extra) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Topic_Extra.Descriptor instead.
func (Topic_Extra) EnumDescriptor() ([]byte, []int) {
	return file_eolymp_atlas_topic_proto_rawDescGZIP(), []int{0, 0}
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Keywords      []string               `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Variants      []*Topic_Variant       `protobuf:"bytes,100,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_eolymp_atlas_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_topic_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Topic) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Topic) GetVariants() []*Topic_Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Topic_Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Keywords      []string               `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic_Variant) Reset() {
	*x = Topic_Variant{}
	mi := &file_eolymp_atlas_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic_Variant) ProtoMessage() {}

func (x *Topic_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_atlas_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic_Variant.ProtoReflect.Descriptor instead.
func (*Topic_Variant) Descriptor() ([]byte, []int) {
	return file_eolymp_atlas_topic_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Topic_Variant) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Topic_Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic_Variant) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Topic_Variant) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_eolymp_atlas_topic_proto protoreflect.FileDescriptor

const file_eolymp_atlas_topic_proto_rawDesc = "" +
	"\n" +
	"\x18eolymp/atlas/topic.proto\x12\feolymp.atlas\"\xb1\x02\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\x127\n" +
	"\bvariants\x18d \x03(\v2\x1b.eolymp.atlas.Topic.VariantR\bvariants\x1ak\n" +
	"\aVariant\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\"(\n" +
	"\x05Extra\x12\x11\n" +
	"\rUNKNOWN_EXTRA\x10\x00\x12\f\n" +
	"\bVARIANTS\x10\x01B-Z+github.com/eolymp/go-sdk/eolymp/atlas;atlasb\x06proto3"

var (
	file_eolymp_atlas_topic_proto_rawDescOnce sync.Once
	file_eolymp_atlas_topic_proto_rawDescData []byte
)

func file_eolymp_atlas_topic_proto_rawDescGZIP() []byte {
	file_eolymp_atlas_topic_proto_rawDescOnce.Do(func() {
		file_eolymp_atlas_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eolymp_atlas_topic_proto_rawDesc), len(file_eolymp_atlas_topic_proto_rawDesc)))
	})
	return file_eolymp_atlas_topic_proto_rawDescData
}

var file_eolymp_atlas_topic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eolymp_atlas_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_eolymp_atlas_topic_proto_goTypes = []any{
	(Topic_Extra)(0),      // 0: eolymp.atlas.Topic.Extra
	(*Topic)(nil),         // 1: eolymp.atlas.Topic
	(*Topic_Variant)(nil), // 2: eolymp.atlas.Topic.Variant
}
var file_eolymp_atlas_topic_proto_depIdxs = []int32{
	2, // 0: eolymp.atlas.Topic.variants:type_name -> eolymp.atlas.Topic.Variant
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eolymp_atlas_topic_proto_init() }
func file_eolymp_atlas_topic_proto_init() {
	if File_eolymp_atlas_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eolymp_atlas_topic_proto_rawDesc), len(file_eolymp_atlas_topic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eolymp_atlas_topic_proto_goTypes,
		DependencyIndexes: file_eolymp_atlas_topic_proto_depIdxs,
		EnumInfos:         file_eolymp_atlas_topic_proto_enumTypes,
		MessageInfos:      file_eolymp_atlas_topic_proto_msgTypes,
	}.Build()
	File_eolymp_atlas_topic_proto = out.File
	file_eolymp_atlas_topic_proto_goTypes = nil
	file_eolymp_atlas_topic_proto_depIdxs = nil
}
