// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.1
// source: eolymp/drive/drive.proto

package drive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Drive_UploadFile_FullMethodName              = "/eolymp.drive.Drive/UploadFile"
	Drive_DescribeFile_FullMethodName            = "/eolymp.drive.Drive/DescribeFile"
	Drive_ListFiles_FullMethodName               = "/eolymp.drive.Drive/ListFiles"
	Drive_UpdateFile_FullMethodName              = "/eolymp.drive.Drive/UpdateFile"
	Drive_DeleteFile_FullMethodName              = "/eolymp.drive.Drive/DeleteFile"
	Drive_StartMultipartUpload_FullMethodName    = "/eolymp.drive.Drive/StartMultipartUpload"
	Drive_UploadPart_FullMethodName              = "/eolymp.drive.Drive/UploadPart"
	Drive_CompleteMultipartUpload_FullMethodName = "/eolymp.drive.Drive/CompleteMultipartUpload"
)

// DriveClient is the client API for Drive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriveClient interface {
	UploadFile(ctx context.Context, in *UploadFileInput, opts ...grpc.CallOption) (*UploadFileOutput, error)
	DescribeFile(ctx context.Context, in *DescribeFileInput, opts ...grpc.CallOption) (*DescribeFileOutput, error)
	ListFiles(ctx context.Context, in *ListFilesInput, opts ...grpc.CallOption) (*ListFilesOutput, error)
	UpdateFile(ctx context.Context, in *UpdateFileInput, opts ...grpc.CallOption) (*UpdateFileOutput, error)
	DeleteFile(ctx context.Context, in *DeleteFileInput, opts ...grpc.CallOption) (*DeleteFileOutput, error)
	StartMultipartUpload(ctx context.Context, in *StartMultipartUploadInput, opts ...grpc.CallOption) (*StartMultipartUploadOutput, error)
	UploadPart(ctx context.Context, in *UploadPartInput, opts ...grpc.CallOption) (*UploadPartOutput, error)
	CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadInput, opts ...grpc.CallOption) (*CompleteMultipartUploadOutput, error)
}

type driveClient struct {
	cc grpc.ClientConnInterface
}

func NewDriveClient(cc grpc.ClientConnInterface) DriveClient {
	return &driveClient{cc}
}

func (c *driveClient) UploadFile(ctx context.Context, in *UploadFileInput, opts ...grpc.CallOption) (*UploadFileOutput, error) {
	out := new(UploadFileOutput)
	err := c.cc.Invoke(ctx, Drive_UploadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) DescribeFile(ctx context.Context, in *DescribeFileInput, opts ...grpc.CallOption) (*DescribeFileOutput, error) {
	out := new(DescribeFileOutput)
	err := c.cc.Invoke(ctx, Drive_DescribeFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) ListFiles(ctx context.Context, in *ListFilesInput, opts ...grpc.CallOption) (*ListFilesOutput, error) {
	out := new(ListFilesOutput)
	err := c.cc.Invoke(ctx, Drive_ListFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) UpdateFile(ctx context.Context, in *UpdateFileInput, opts ...grpc.CallOption) (*UpdateFileOutput, error) {
	out := new(UpdateFileOutput)
	err := c.cc.Invoke(ctx, Drive_UpdateFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) DeleteFile(ctx context.Context, in *DeleteFileInput, opts ...grpc.CallOption) (*DeleteFileOutput, error) {
	out := new(DeleteFileOutput)
	err := c.cc.Invoke(ctx, Drive_DeleteFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) StartMultipartUpload(ctx context.Context, in *StartMultipartUploadInput, opts ...grpc.CallOption) (*StartMultipartUploadOutput, error) {
	out := new(StartMultipartUploadOutput)
	err := c.cc.Invoke(ctx, Drive_StartMultipartUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) UploadPart(ctx context.Context, in *UploadPartInput, opts ...grpc.CallOption) (*UploadPartOutput, error) {
	out := new(UploadPartOutput)
	err := c.cc.Invoke(ctx, Drive_UploadPart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadInput, opts ...grpc.CallOption) (*CompleteMultipartUploadOutput, error) {
	out := new(CompleteMultipartUploadOutput)
	err := c.cc.Invoke(ctx, Drive_CompleteMultipartUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriveServer is the server API for Drive service.
// All implementations should embed UnimplementedDriveServer
// for forward compatibility
type DriveServer interface {
	UploadFile(context.Context, *UploadFileInput) (*UploadFileOutput, error)
	DescribeFile(context.Context, *DescribeFileInput) (*DescribeFileOutput, error)
	ListFiles(context.Context, *ListFilesInput) (*ListFilesOutput, error)
	UpdateFile(context.Context, *UpdateFileInput) (*UpdateFileOutput, error)
	DeleteFile(context.Context, *DeleteFileInput) (*DeleteFileOutput, error)
	StartMultipartUpload(context.Context, *StartMultipartUploadInput) (*StartMultipartUploadOutput, error)
	UploadPart(context.Context, *UploadPartInput) (*UploadPartOutput, error)
	CompleteMultipartUpload(context.Context, *CompleteMultipartUploadInput) (*CompleteMultipartUploadOutput, error)
}

// UnimplementedDriveServer should be embedded to have forward compatible implementations.
type UnimplementedDriveServer struct {
}

func (UnimplementedDriveServer) UploadFile(context.Context, *UploadFileInput) (*UploadFileOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedDriveServer) DescribeFile(context.Context, *DescribeFileInput) (*DescribeFileOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeFile not implemented")
}
func (UnimplementedDriveServer) ListFiles(context.Context, *ListFilesInput) (*ListFilesOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedDriveServer) UpdateFile(context.Context, *UpdateFileInput) (*UpdateFileOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFile not implemented")
}
func (UnimplementedDriveServer) DeleteFile(context.Context, *DeleteFileInput) (*DeleteFileOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedDriveServer) StartMultipartUpload(context.Context, *StartMultipartUploadInput) (*StartMultipartUploadOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMultipartUpload not implemented")
}
func (UnimplementedDriveServer) UploadPart(context.Context, *UploadPartInput) (*UploadPartOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedDriveServer) CompleteMultipartUpload(context.Context, *CompleteMultipartUploadInput) (*CompleteMultipartUploadOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMultipartUpload not implemented")
}

// UnsafeDriveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriveServer will
// result in compilation errors.
type UnsafeDriveServer interface {
	mustEmbedUnimplementedDriveServer()
}

func RegisterDriveServer(s grpc.ServiceRegistrar, srv DriveServer) {
	s.RegisterService(&Drive_ServiceDesc, srv)
}

func _Drive_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).UploadFile(ctx, req.(*UploadFileInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_DescribeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeFileInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).DescribeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_DescribeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).DescribeFile(ctx, req.(*DescribeFileInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).ListFiles(ctx, req.(*ListFilesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_UpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).UpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_UpdateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).UpdateFile(ctx, req.(*UpdateFileInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).DeleteFile(ctx, req.(*DeleteFileInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_StartMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMultipartUploadInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).StartMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_StartMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).StartMultipartUpload(ctx, req.(*StartMultipartUploadInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_UploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPartInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).UploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_UploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).UploadPart(ctx, req.(*UploadPartInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_CompleteMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartUploadInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).CompleteMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drive_CompleteMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).CompleteMultipartUpload(ctx, req.(*CompleteMultipartUploadInput))
	}
	return interceptor(ctx, in, info, handler)
}

// Drive_ServiceDesc is the grpc.ServiceDesc for Drive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Drive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eolymp.drive.Drive",
	HandlerType: (*DriveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _Drive_UploadFile_Handler,
		},
		{
			MethodName: "DescribeFile",
			Handler:    _Drive_DescribeFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _Drive_ListFiles_Handler,
		},
		{
			MethodName: "UpdateFile",
			Handler:    _Drive_UpdateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _Drive_DeleteFile_Handler,
		},
		{
			MethodName: "StartMultipartUpload",
			Handler:    _Drive_StartMultipartUpload_Handler,
		},
		{
			MethodName: "UploadPart",
			Handler:    _Drive_UploadPart_Handler,
		},
		{
			MethodName: "CompleteMultipartUpload",
			Handler:    _Drive_CompleteMultipartUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eolymp/drive/drive.proto",
}
