// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: eolymp/notify/channel_service.proto

package notify

import (
	_ "github.com/eolymp/go-sdk/eolymp/annotations"
	wellknown "github.com/eolymp/go-sdk/eolymp/wellknown"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChannelInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelInput) Reset() {
	*x = CreateChannelInput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelInput) ProtoMessage() {}

func (x *CreateChannelInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelInput.ProtoReflect.Descriptor instead.
func (*CreateChannelInput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChannelInput) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type CreateChannelOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelOutput) Reset() {
	*x = CreateChannelOutput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelOutput) ProtoMessage() {}

func (x *CreateChannelOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelOutput.ProtoReflect.Descriptor instead.
func (*CreateChannelOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChannelOutput) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type UpdateChannelInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Channel       *Channel_Patch         `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelInput) Reset() {
	*x = UpdateChannelInput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelInput) ProtoMessage() {}

func (x *UpdateChannelInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelInput.ProtoReflect.Descriptor instead.
func (*UpdateChannelInput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateChannelInput) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UpdateChannelInput) GetChannel() *Channel_Patch {
	if x != nil {
		return x.Channel
	}
	return nil
}

type UpdateChannelOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelOutput) Reset() {
	*x = UpdateChannelOutput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelOutput) ProtoMessage() {}

func (x *UpdateChannelOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelOutput.ProtoReflect.Descriptor instead.
func (*UpdateChannelOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{3}
}

type DeleteChannelInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelInput) Reset() {
	*x = DeleteChannelInput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelInput) ProtoMessage() {}

func (x *DeleteChannelInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelInput.ProtoReflect.Descriptor instead.
func (*DeleteChannelInput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChannelInput) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type DeleteChannelOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelOutput) Reset() {
	*x = DeleteChannelOutput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelOutput) ProtoMessage() {}

func (x *DeleteChannelOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelOutput.ProtoReflect.Descriptor instead.
func (*DeleteChannelOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{5}
}

type DescribeChannelInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeChannelInput) Reset() {
	*x = DescribeChannelInput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeChannelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeChannelInput) ProtoMessage() {}

func (x *DescribeChannelInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeChannelInput.ProtoReflect.Descriptor instead.
func (*DescribeChannelInput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeChannelInput) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type DescribeChannelOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeChannelOutput) Reset() {
	*x = DescribeChannelOutput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeChannelOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeChannelOutput) ProtoMessage() {}

func (x *DescribeChannelOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeChannelOutput.ProtoReflect.Descriptor instead.
func (*DescribeChannelOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeChannelOutput) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ListChannelsInput struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Offset        int32                     `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int32                     `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	Search        string                    `protobuf:"bytes,20,opt,name=search,proto3" json:"search,omitempty"`
	Filters       *ListChannelsInput_Filter `protobuf:"bytes,40,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsInput) Reset() {
	*x = ListChannelsInput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsInput) ProtoMessage() {}

func (x *ListChannelsInput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsInput.ProtoReflect.Descriptor instead.
func (*ListChannelsInput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListChannelsInput) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListChannelsInput) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListChannelsInput) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListChannelsInput) GetFilters() *ListChannelsInput_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListChannelsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*Channel             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsOutput) Reset() {
	*x = ListChannelsOutput{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsOutput) ProtoMessage() {}

func (x *ListChannelsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsOutput.ProtoReflect.Descriptor instead.
func (*ListChannelsOutput) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListChannelsOutput) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListChannelsOutput) GetItems() []*Channel {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListChannelsInput_Filter struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            []*wellknown.ExpressionID `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsInput_Filter) Reset() {
	*x = ListChannelsInput_Filter{}
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsInput_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsInput_Filter) ProtoMessage() {}

func (x *ListChannelsInput_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_eolymp_notify_channel_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsInput_Filter.ProtoReflect.Descriptor instead.
func (*ListChannelsInput_Filter) Descriptor() ([]byte, []int) {
	return file_eolymp_notify_channel_service_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListChannelsInput_Filter) GetId() []*wellknown.ExpressionID {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_eolymp_notify_channel_service_proto protoreflect.FileDescriptor

const file_eolymp_notify_channel_service_proto_rawDesc = "" +
	"\n" +
	"#eolymp/notify/channel_service.proto\x12\reolymp.notify\x1a\x1eeolymp/annotations/audit.proto\x1a\x1deolymp/annotations/http.proto\x1a\"eolymp/annotations/namespace.proto\x1a\"eolymp/annotations/ratelimit.proto\x1a\x1eeolymp/annotations/scope.proto\x1a\x1beolymp/notify/channel.proto\x1a!eolymp/wellknown/expression.proto\"F\n" +
	"\x12CreateChannelInput\x120\n" +
	"\achannel\x18\x01 \x01(\v2\x16.eolymp.notify.ChannelR\achannel\"4\n" +
	"\x13CreateChannelOutput\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"k\n" +
	"\x12UpdateChannelInput\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x126\n" +
	"\achannel\x18\x03 \x01(\v2\x1c.eolymp.notify.Channel.PatchR\achannel\"\x15\n" +
	"\x13UpdateChannelOutput\"3\n" +
	"\x12DeleteChannelInput\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x15\n" +
	"\x13DeleteChannelOutput\"5\n" +
	"\x14DescribeChannelInput\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"I\n" +
	"\x15DescribeChannelOutput\x120\n" +
	"\achannel\x18\x01 \x01(\v2\x16.eolymp.notify.ChannelR\achannel\"\xd4\x01\n" +
	"\x11ListChannelsInput\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x05R\x06offset\x12\x12\n" +
	"\x04size\x18\v \x01(\x05R\x04size\x12\x16\n" +
	"\x06search\x18\x14 \x01(\tR\x06search\x12A\n" +
	"\afilters\x18( \x01(\v2'.eolymp.notify.ListChannelsInput.FilterR\afilters\x1a8\n" +
	"\x06Filter\x12.\n" +
	"\x02id\x18\x01 \x03(\v2\x1e.eolymp.wellknown.ExpressionIDR\x02id\"X\n" +
	"\x12ListChannelsOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.eolymp.notify.ChannelR\x05items2\xf0\x06\n" +
	"\x0eChannelService\x12\x9c\x01\n" +
	"\rCreateChannel\x12!.eolymp.notify.CreateChannelInput\x1a\".eolymp.notify.CreateChannelOutput\"D\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\xa0@\xf8\xe2\n" +
	"\x14\x82\xe3\n" +
	"\x18\x8a\xe3\n" +
	"\x14notify:channel:write\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x02\x82\xd3\xe4\x93\x02\v\"\t/channels\x12\xa9\x01\n" +
	"\rUpdateChannel\x12!.eolymp.notify.UpdateChannelInput\x1a\".eolymp.notify.UpdateChannelOutput\"Q\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\xa0@\xf8\xe2\n" +
	"\x14\x82\xe3\n" +
	"\x18\x8a\xe3\n" +
	"\x14notify:channel:write\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x02\x82\xd3\xe4\x93\x02\x18\x1a\x16/channels/{channel_id}\x12\xa9\x01\n" +
	"\rDeleteChannel\x12!.eolymp.notify.DeleteChannelInput\x1a\".eolymp.notify.DeleteChannelOutput\"Q\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\xa0@\xf8\xe2\n" +
	"\x14\x82\xe3\n" +
	"\x18\x8a\xe3\n" +
	"\x14notify:channel:write\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x03\x82\xd3\xe4\x93\x02\x18*\x16/channels/{channel_id}\x12\xae\x01\n" +
	"\x0fDescribeChannel\x12#.eolymp.notify.DescribeChannelInput\x1a$.eolymp.notify.DescribeChannelOutput\"P\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\xa0A\xf8\xe2\n" +
	"d\x82\xe3\n" +
	"\x17\x8a\xe3\n" +
	"\x13notify:channel:read\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x01\x82\xd3\xe4\x93\x02\x18\x12\x16/channels/{channel_id}\x12\x98\x01\n" +
	"\fListChannels\x12 .eolymp.notify.ListChannelsInput\x1a!.eolymp.notify.ListChannelsOutput\"C\xea\xe2\n" +
	"\v\xf5\xe2\n" +
	"\x00\x00\xa0A\xf8\xe2\n" +
	"d\x82\xe3\n" +
	"\x17\x8a\xe3\n" +
	"\x13notify:channel:read\xa2\xe3\n" +
	"\x04\xa8\xe3\n" +
	"\x01\x82\xd3\xe4\x93\x02\v\x12\t/channels\x1a\x1b\x82\xf0\xf0\xe4\x01\x15eolymp.universe.SpaceB/Z-github.com/eolymp/go-sdk/eolymp/notify;notifyb\x06proto3"

var (
	file_eolymp_notify_channel_service_proto_rawDescOnce sync.Once
	file_eolymp_notify_channel_service_proto_rawDescData []byte
)

func file_eolymp_notify_channel_service_proto_rawDescGZIP() []byte {
	file_eolymp_notify_channel_service_proto_rawDescOnce.Do(func() {
		file_eolymp_notify_channel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eolymp_notify_channel_service_proto_rawDesc), len(file_eolymp_notify_channel_service_proto_rawDesc)))
	})
	return file_eolymp_notify_channel_service_proto_rawDescData
}

var file_eolymp_notify_channel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_eolymp_notify_channel_service_proto_goTypes = []any{
	(*CreateChannelInput)(nil),       // 0: eolymp.notify.CreateChannelInput
	(*CreateChannelOutput)(nil),      // 1: eolymp.notify.CreateChannelOutput
	(*UpdateChannelInput)(nil),       // 2: eolymp.notify.UpdateChannelInput
	(*UpdateChannelOutput)(nil),      // 3: eolymp.notify.UpdateChannelOutput
	(*DeleteChannelInput)(nil),       // 4: eolymp.notify.DeleteChannelInput
	(*DeleteChannelOutput)(nil),      // 5: eolymp.notify.DeleteChannelOutput
	(*DescribeChannelInput)(nil),     // 6: eolymp.notify.DescribeChannelInput
	(*DescribeChannelOutput)(nil),    // 7: eolymp.notify.DescribeChannelOutput
	(*ListChannelsInput)(nil),        // 8: eolymp.notify.ListChannelsInput
	(*ListChannelsOutput)(nil),       // 9: eolymp.notify.ListChannelsOutput
	(*ListChannelsInput_Filter)(nil), // 10: eolymp.notify.ListChannelsInput.Filter
	(*Channel)(nil),                  // 11: eolymp.notify.Channel
	(*Channel_Patch)(nil),            // 12: eolymp.notify.Channel.Patch
	(*wellknown.ExpressionID)(nil),   // 13: eolymp.wellknown.ExpressionID
}
var file_eolymp_notify_channel_service_proto_depIdxs = []int32{
	11, // 0: eolymp.notify.CreateChannelInput.channel:type_name -> eolymp.notify.Channel
	12, // 1: eolymp.notify.UpdateChannelInput.channel:type_name -> eolymp.notify.Channel.Patch
	11, // 2: eolymp.notify.DescribeChannelOutput.channel:type_name -> eolymp.notify.Channel
	10, // 3: eolymp.notify.ListChannelsInput.filters:type_name -> eolymp.notify.ListChannelsInput.Filter
	11, // 4: eolymp.notify.ListChannelsOutput.items:type_name -> eolymp.notify.Channel
	13, // 5: eolymp.notify.ListChannelsInput.Filter.id:type_name -> eolymp.wellknown.ExpressionID
	0,  // 6: eolymp.notify.ChannelService.CreateChannel:input_type -> eolymp.notify.CreateChannelInput
	2,  // 7: eolymp.notify.ChannelService.UpdateChannel:input_type -> eolymp.notify.UpdateChannelInput
	4,  // 8: eolymp.notify.ChannelService.DeleteChannel:input_type -> eolymp.notify.DeleteChannelInput
	6,  // 9: eolymp.notify.ChannelService.DescribeChannel:input_type -> eolymp.notify.DescribeChannelInput
	8,  // 10: eolymp.notify.ChannelService.ListChannels:input_type -> eolymp.notify.ListChannelsInput
	1,  // 11: eolymp.notify.ChannelService.CreateChannel:output_type -> eolymp.notify.CreateChannelOutput
	3,  // 12: eolymp.notify.ChannelService.UpdateChannel:output_type -> eolymp.notify.UpdateChannelOutput
	5,  // 13: eolymp.notify.ChannelService.DeleteChannel:output_type -> eolymp.notify.DeleteChannelOutput
	7,  // 14: eolymp.notify.ChannelService.DescribeChannel:output_type -> eolymp.notify.DescribeChannelOutput
	9,  // 15: eolymp.notify.ChannelService.ListChannels:output_type -> eolymp.notify.ListChannelsOutput
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_eolymp_notify_channel_service_proto_init() }
func file_eolymp_notify_channel_service_proto_init() {
	if File_eolymp_notify_channel_service_proto != nil {
		return
	}
	file_eolymp_notify_channel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eolymp_notify_channel_service_proto_rawDesc), len(file_eolymp_notify_channel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eolymp_notify_channel_service_proto_goTypes,
		DependencyIndexes: file_eolymp_notify_channel_service_proto_depIdxs,
		MessageInfos:      file_eolymp_notify_channel_service_proto_msgTypes,
	}.Build()
	File_eolymp_notify_channel_service_proto = out.File
	file_eolymp_notify_channel_service_proto_goTypes = nil
	file_eolymp_notify_channel_service_proto_depIdxs = nil
}
